- src/components/PriceCard.vue
- src/routes.js
- src/services/api.js
- src/views/PriceList.vue
- New nav drawer item "Last prices"
- show most recent prices first
- simple card with price / product / location details (dedicated component)
- currency : avoid hardcoded "€"
- quantity : display products with "L"
- bigger image : 2 columns instead of "card"
- search, reorder, filter
- what to display if information missing ?
> feat: simple list of last added prices

- package.json
- src/views/AddPriceSingle.vue
- yarn.lock
Use [compressor.js](https://github.com/fengyuanchen/compressorjs) to compress the proof image before uploading it to the backend.
Tested with 7.1 MB JPEG image --> 677 KB output
> feat: compress proof image before upload

- src/services/api.js
- src/views/AddPriceSingle.vue
When uploading a proof, also send `type=PRICE_TAG` info
Related backend PR : https://github.com/openfoodfacts/open-prices/pull/95
> feat: send proof type on proof upload

- src/views/AddPriceSingle.vue
Proof upload form changes:
- change icon (square -> circle)
- avoid overflow
- responsive : display image on the right column on bigger screens
- improve loading (hide error, show success)
> feat: price create form: improve a bit the proof upload (responsive, overflow, icon)

- src/views/AddPriceSingle.vue
Following #41 
We needed to manage webp images in the backend (PR here: https://github.com/openfoodfacts/open-prices/pull/98) before using this filetype in the frontend
> feat: price create form: convert proof image to webp before upload

- src/views/AddPriceSingle.vue
Improve the UI of the price create form: 
- split the current 2nd step into 2 : there are now 3 steps
- show a green border on the step card if it is filled
- make the "Create" button green when the form is ready
> feat(price create form): 3 steps, green border on step filled

- package.json
- src/components/Header.vue
- src/main.js
- src/router.js
- src/services/api.js
- src/store.js
- src/views/SignIn.vue
- src/views/UserDashboard.vue
- yarn.lock
We currently use cookies to store username & token. But they seem to expire quite quickly (need to re-login often).
It's a good opportunity to replace this with a store : [pinia](https://pinia.vuejs.org/)
Next step: persist the store in the localstorage
> refactor: replace cookie storage with a store (pinia)

- src/components/LocationSelector.vue
- src/services/api.js
- src/store.js
- src/utils.js
- src/views/AddPriceSingle.vue
Following #70
- manage `last_currency_used` in state (used to init price create form)
- manage `recent_locations` in state (and make it fully reactive)
> refactor: continue replacing current localStorage usage with new store

- src/services/api.js
- src/views/AddPriceSingle.vue
On step 2 of the price create form, when the user scans a barcode, we fetch data from OFF to provide a visual feedback (name of the product, image)
> feat(price create form): on barcode scan, fetch product details from OFF

- src/router.js
- src/views/UserDetail.vue
When selecting a user from a PriceCard, we are now presented with a User page:
- basic info (username)
- last prices + count
API call made available thanks to this commit : https://github.com/openfoodfacts/open-prices/commit/6e922f30029a9f9558ff070d3dc7c4330dd7e08f
> feat(user detail): new basic User detail page

- src/components/PriceCard.vue
Following #82 we can now add prices with label tags (only 'organic' for now)
We wish to display this information in the price card
> feat(price card): add label tags

- src/components/PriceCard.vue
Following #85 we can now add prices with origin tag
We wish to display this information in the price card
> feat(price card): add origin tag info

- src/services/api.js
- src/views/LocationDetail.vue
- src/views/PriceList.vue
- src/views/ProductDetail.vue
- src/views/Stats.vue
- src/views/UserDashboard.vue
- src/views/UserDetail.vue
We currently fetch prices by batches of 50, which is often slow to load...
- reduced the size to 10
- add a load more button to allow "scrolling"
> feat: fetch latest prices by batches of 10 + load more button

- src/components/PriceCard.vue
- src/utils.js
- src/views/ProductDetail.vue
Following #55
Allow displaying the product page for categories, such as `/products/en:tomatoes`
To fetch prices per category_tag, we'll need to merge https://github.com/openfoodfacts/open-prices/pull/113 in the backend
> feat(product detail): manage category tags

- src/views/AddPriceSingle.vue
Currently the price proof is asked first. We change this to the product scanning, so that we can display info about the product (details, number of scans...)
- move product selection first
- group price & proof together
- change button icons (scan product / image proof / location find)
|Before|After|
|---|---|
|1. Proof<br>2. Product & price<br>3. Location & date|1. Product<br>2. Price & proof<br>3. Location & date|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/4a5bb04e-b2d6-4bf0-97a4-3624eba346c8)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/65817306-9f71-44c9-84ef-bdc10e72280b)|
> feat(price create form): move product scanning first

- src/components/PriceCard.vue
Reduce the size of the bottom labels (similar to the product labels above)
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/13057baa-6842-4296-9f39-3d61abdba206)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/36604c6a-9aa4-450c-af30-9334919911c9)|
> fix(price card): make bottom labels smaller

- src/components/PriceCard.vue
- src/utils.js
Price card : 
- fix old dates later than 4 weeks (was blank before)
- remove 'ago' to reduce size
- show tooltip on created label hover
|Before|After|
|---|---|
|![Screenshot from 2024-01-07 09-40-39](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/62f3beeb-a166-4fce-bf00-d624d87e9e4c)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/5ef7da04-2328-4662-ad8b-47d0158eac8a)|
> fix(price card): improve created date info (further weeks, remove ago, tooltip)

- src/components/PriceCard.vue
- src/services/api.js
- src/views/ProductDetail.vue
Thanks to https://github.com/openfoodfacts/open-prices/pull/106 we can now retrieve product info by code.
This change will simplify and clarify urls : 
- before `/products/12`
- after `/products/8001505005707`
Also improve display of unknown product (show card with product code)
> feat(product page): change url (code instead of id)

- src/components/PriceCard.vue
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/d002d1d6-a475-46e1-a627-1fb6f2f0d99f)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/8fdf29ff-18b5-4d22-952b-d46212f4126f)|
> fix(price card): split product brands into seperate labels

- src/services/api.js
- src/views/AddPriceSingle.vue
- src/views/UserSettings.vue
Following #121 the currency is now editable in the user settings.
We can hide it in the price create form, and display it as a suffix in the price field.
||Image|
|---|---|
|Before|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/3622d6af-9882-4058-832a-020474b176f0)|
|After|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/8e14a854-aee3-4557-bbc3-479c38b21157)|
> feat(price create form): hide currency selector

- src/components/PriceCard.vue
- src/router.js
- src/views/BrandDetail.vue
For each product we have the `brands` info. And since #109 they are new split into different chips if there are multiple.
New page to display the brand's products
Accessible when clicking on a product's brand
> feat(brand detail): new Brand detail page

- src/components/PriceCard.vue
Thanks to https://github.com/openfoodfacts/open-prices/pull/129 we now have an up-to-date `price_count` field for each Product.
We can display it :)
> feat(price card): show product price_count

- src/components/Header.vue
- src/views/ProductList.vue
Allow ordering the top products by "Number of prices" (was "popularity" = "number of scans" by default before)
> feat(product list): add order button to toggle between scan & price count

- src/views/AddPriceSingle.vue
In the price create form, when a user scans a product, we currently fetch data from OFF (see #73).
But we now have all the products in OP + their `price_count` - which is an interesting info to display to the users.
So we switch the API call :)
> feat(price create form): on barcode scan, fetch product details from OP (instead of OFF)

- src/views/Stats.vue
Now that we have the `Product.price_count` info, we can display additional stats
(test data)
> feat(stats): new stats on products (total & with prices)

- src/views/Stats.vue
> feat(stats): new location total stat

- src/router.js
- src/views/LocationList.vue
Similar to #113
Following #138 
And thanks to https://github.com/openfoodfacts/open-prices/pull/140 we now have a new field `Location.price_count`
Creation of a new `/locations` page ordered by price count
This page is accessible from the left drawer
> feat(location list): new location list page ordered by price_count

- src/router.js
- src/views/UserList.vue
Similar to #113 & #145
Following #148
And thanks to https://github.com/openfoodfacts/open-prices/pull/143 we now have a new field `User.price_count`
Creation of a new `/users` page ordered by price count (only users with at least 1 price)
This page is accessible from the left drawer
> feat(user list): new user list page ordered by price_count

- src/components/BarcodeManualInput.vue
- src/i18n/locales/en.json
- src/views/AddPriceSingle.vue
Add a link next to the barcode scan button, that allows entering the barcode manually
Why a popup ? So that we can fetch the product details on submit
> feat(price create form): allow typing the barcode manually

- src/i18n/locales/en.json
- src/views/AddPriceSingle.vue
- src/views/ProductDetail.vue
When clicking on "Add a price" in the product detail page, the price create form is now initialisez with the corresponding product code
By passing the code as a URL param
`/add/single?code=8001505005592`
> feat(price create form): init form with code param from product detail CTA

- src/i18n/locales/en.json
- src/views/AddPriceSingle.vue
Allow the user to indicate that the price has a discount.
A new mandatory field pops up asking for the non-discounted price
|Before|Without discount|With discount|
|---|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/a6f8b1ed-62cf-4b9a-9364-a54a89de5c35)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/fe35299c-28ce-4f7d-930c-7ac176abb1cc)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/047a8f80-444b-4410-aa88-49c4ad66309a)|
> feat(price create form): manage discounted prices

- src/components/PriceCard.vue
- src/i18n/locales/en.json
Following #171
If the price is discounted, then display it in the Price Card
|Without discount|With discount|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/48abd024-ab54-4a9b-b2a8-9159c71a1a46)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/b4e7b685-1bde-4cf3-992a-d629330207d7)|
> feat(price card): show discount tag with tooltip

- crowdin.yml
- Replace commit message from crowdin with the same message. This should simplify a squash to only display this message
- Added [ci skip] tag to not trigger a build for each commit
https://developer.crowdin.com/configuration-file/
> fix(crowdin): change config to simplify PR from crowdin

- .env.preprod
- .env.prod
- public/manifest.local.json
- public/manifest.preprod.json
- public/manifest.prod.json
Following #93 
- split prod & preprod manifest configuration
- improved the manifest config by adding a `scope`. Hopefully this will help with external links.
- also reduced the name to `OpenPrices` to match with the `OpenFoodFacts` android app name.
> feat(PWA): improve manifest configuration

- src/components/PriceFooter.vue
- src/components/PriceProof.vue
- src/i18n/locales/en.json
Allow users to display price proofs
|Price card|Proof dialog|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/ba114f78-8c68-4e28-abd8-68d782bc8eae)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/625b3c82-3d1f-4e50-8fc9-e6a355727d9d)|
> feat(price card): allow displaying price proofs (if is public)

- src/components/PricePrice.vue
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
Following #171 & #173
And thanks to https://github.com/openfoodfacts/open-prices/pull/163
A new field `price_is_discounted` stores the info in the price has a discount or not.
The user is not forced to enter the `price_without_discount` anymore
> feat: improve price discount (full_price not mandatory anymore)

- src/i18n/locales/en.json
- src/router.js
- src/views/UserDashboard.vue
- src/views/UserDashboardPriceList.vue
Start improving the user dashboard
- add link to settings
- move price list to separate page
- upcoming PR : list of proofs
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/545751b9-5bd7-4fcf-bb0c-8c4893796cb5)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/02cd9075-2286-4daa-91bf-9543c0d6df3e)|
> feat(dashboard): move prices to seperate page

- CONTRIBUTING.md
I propose to move the instruction directly in the README.md to avoid contributor missing it. For now, we don't miss places on this document so no need to split
Added a section for newbies to give them correct tools, plus a direct link to the server project
> docs: improve setup instructions

- src/components/PricePrice.vue
- src/i18n/locales/en.json
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
- Added a choice selector to enable changing `price_per` between `KILOGRAM ` or `UNIT` when inputting a price for a product without barcode
- Default behavior: automatically set to Kilogram
> feat: add category price per unit toggle

- src/components/ProofCard.vue
- src/components/ProofDeleteChip.vue
- src/components/ProofFooter.vue
- src/i18n/locales/en.json
- src/services/api.js
Thanks to https://github.com/openfoodfacts/open-prices/pull/197 a user will be able to delete its own proofs
- added a chip in the proof card footer
- confirmation dialog
- the proof must be owned by the user + have 0 prices attached
||Image|
|---|---|
|Proof card|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/2c047e34-f5e5-4105-9c68-3587ee60b852)|
|Confirmation dialog|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/7f750c27-dc28-451b-8b69-e22444b901b9)|
> feat: allow users to delete its own proofs

- src/components/PriceCard.vue
- src/components/PricePrice.vue
- src/components/ProductCard.vue
- src/i18n/locales/en.json
Thanks to https://github.com/openfoodfacts/open-prices/pull/194
We have a new field `Product.product_quantity_unit`
When filled, we will be able to differenciate kg & L products
> feat: display kg / L depending on product_quantity_unit

- src/components/PriceCard.vue
- src/components/PricePrice.vue
- src/components/ProductCard.vue
- src/components/ProductQuantityChip.vue
- src/i18n/locales/en.json
Similar to #311
Better display the product quantity (`ProductCard`)
New `ProductQuantityChip`
||Image|
|---|---|
|Before|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/ef183ec0-50bd-4cfe-834c-8233255acf04)|
|After|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/5f11a348-08cc-44cf-a607-137880b887e5)|
> feat: display product quantity (g or mL) depending on product_quantity_unit

- src/components/Header.vue
The header's background color has been updated to RGB(242, 233, 228) to align it with the color scheme used in other OFF projects.
Before the changes:
After the header background color has been updated:
#298
> feat: header background color (same as OFF)

- src/utils.js
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
Following #321 (and similar to #275)
- we now have the translated origins
- we can display the corresponding origin list depending on the user locale
example with French locale
> feat(l10n): translate origin list in price add form depending on user locale

- src/components/PricePrice.vue
- src/components/RelativeDateTimeChip.vue
- added possibility to show on click tooltips for "discount" and "date" for price cards since there is hovering is not feasible on touchscreen
> fix: show tooltip on click (discount, date)

- data/languages/generate_languages.py
- src/i18n/data/languages.json
- Some languages had several comma or semicolon separated names or native names, fixed script to take the first one
- Capitalized first letter
> fix(l10n): fix languages with multiple entries in name and native

- src/i18n/locales/en.json
- src/i18n/locales/fr.json
- src/views/AddPriceSingle.vue
Following #164 & #162
Change **Type a barcode** and **Select from gallery** links to buttons
||Image|
|--|---|
|Small screens|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/83106611-a45a-4d04-afb0-6575942b42c5)|
|Larger screens|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/10730549/12ea9747-975a-4c40-9ee9-9fbc09138962)|
> fix: Turn 2 links into real buttons (Type a barcode & Select from gallery)

- src/constants.js
- src/i18n/locales/en.json
- src/views/BrandDetail.vue
- src/views/LocationDetail.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/UserDetail.vue
- With our database of prices growing and huge GDPR import, we need to have different filters to display prices
- Added price ordering by "last created" descending and "date"
- Added price filtering for the last 30 days (can be further improved/reworked)
- Pages concerned: ProductDetail, LocationDetail, UserDetail
- Added a small fix to ProductList to avoid doing an API call when going from ProductList page to any other
Closes #343
> feat: add price filter

- src/components/ProductCard.vue
- src/i18n/locales/en.json
Thanks to the new fields in the backend, we can start displaying a badge with the count
- `Product.categories_tags` : https://github.com/openfoodfacts/open-prices/issues/154
- `Product.labels_tags` : https://github.com/openfoodfacts/open-prices/issues/216
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/ea7794b2-a259-4e5d-b7d7-a96db2aec219)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/2eee9b3c-426c-41b2-888e-0c0c053bd31b)|
> feat(products): display categories & labels count

- src/components/ProductCard.vue
- src/components/ProductCategoriesDialog.vue
- src/i18n/locales/en.json
Following #367
When the user clicks on the new "product categories count chip", a popup opens with the list of the categories.
|Product without categories|Product with categories|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/95b729d5-6434-4f27-af7c-cec06dfa70c2)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/1c3fb181-69d2-4b92-b1ea-86c668ca4c79)|
> feat(products): display popup with product categories

- src/components/ExistingProofDialog.vue
- src/components/ProofCard.vue
- src/components/ProofFooter.vue
- src/components/UserRecentProofsDialog.vue
- src/i18n/locales/en.json
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
Allow user to select an existing proof when adding a price.
This is a WIP and only implemented for addSinglePrice. Please add your feedback to this PR on design and code and I will change / implement further.
A new button allows to open a dialog with the last (max 10) proofs.
They will be displayed in a 5x2 grid.
Selecting one will highlight it and show a confirmation dialog
If "No" is selected, user goes back to choosing the proof.
If "Yes", it closes both dialogs and displays the selected proof as is done for "Camera" or "Gallery" modes
<hr>
PR simplified, no more confirmation dialog, works for both single & multiple price forms, rename "existing" to "recent"
> feat(price create form): allow user to select a recent proof

- src/components/PriceCard.vue
- src/components/PriceFooter.vue
- src/components/ProofCard.vue
- src/components/ProofFooter.vue
- src/components/UserRecentProofsDialog.vue
- src/i18n/locales/en.json
- src/router.js
- src/views/ProofDetail.vue
Thanks to https://github.com/openfoodfacts/open-prices/pull/228 & following #383
Allow users to view more details about their proofs, in a dedicated page
- the proof image & basic info
- the list of prices associated
Link is done via the proof price count chip.
An error message is shown is the proof is not found or not the owner
See prices filtered by a given proof, allow in the future to add a new price for this proof
|Existing proof|Unknown proof|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/be817b72-9146-4ccd-b707-1645a0c7bc9a)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/c427e233-f87e-4f0b-b973-761308b7663f)|
- alternative proof card (horizontal) to better display the info ?
- improve proof footer
- link to …
> feat: new proof detail page

- src/components/OpenFoodFactsButton.vue
- src/components/ProductCard.vue
- src/i18n/locales/en.json
- src/views/ProductDetail.vue
In the product detail page, when the product is not found, we just show a message in red.
This PR does a few things : 
- adds a button to OFF
- changes the title to "<product code>" instead of "unknown product name"
Closes #177
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/df08a3bc-9bcb-434e-beb4-58732185ac22)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/2e2cc6e9-190a-4281-8c34-6c968114e804)|
> fix(product): fix add OFF button if product not found

- src/views/AddPriceSingle.vue
The "Add a price" button from the product page works for products with barcodes - since #168
But the product categories weren't supported.
Closes #351
> fix(price create form): fix form init when coming from category

- src/components/PriceProof.vue
- src/components/ProofCard.vue
- src/components/ProofDeleteChip.vue
- src/components/UserRecentProofsDialog.vue
- src/i18n/locales/en.json
- src/views/ProofDetail.vue
- src/views/UserDashboardProofList.vue
We have duplicated code between ProofCard, PriceProof & ProofDeleteChip.
Added a new prop `hideProofHeader`, so that the ProofCard can be used everywhere !
> refactor: use ProofCard everywhere

- src/components/ProductCard.vue
- src/components/ProductLabelsDialog.vue
- src/i18n/locales/en.json
Similar to #369
When the user clicks on the new "product labels count chip", a popup opens with the list of the labels.
> feat(products): display popup with product labels

- src/services/api.js
Thanks to https://github.com/openfoodfacts/open-prices/issues/236, it is now possible to update a proof fields (`type` and `is_public`)
Created the endpoint on the frontend side
Part of  #363
> feat: add update PATCH proof in api

- src/components/ProductCategoriesDialog.vue
- src/i18n/locales/en.json
- src/router.js
- src/views/CategoryDetail.vue
Similar to #116
When clicking on a product category, display a "category detail" page with : 
- a simple category card at the top
- the category's top products
Dependent on merging this PR in the backend : https://github.com/openfoodfacts/open-prices/pull/234
> feat(category detail): new category detail page

- src/constants.js
In the pages with a list of prices, add a new ordering by "cheapest first"
> feat: new ordering choice by price (lowest first)

- src/constants.js
- src/i18n/locales/en.json
- src/views/LocationDetail.vue
- src/views/ProductDetail.vue
- src/views/UserDetail.vue
Currently the price ordering values are hardcoded in `constants.js`
Refactored to allow translations
> refactor(l10n): allow translation of price ordering options

- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/LocationDetail.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/UserDetail.vue
We are starting to have many pages where the user can order the data (price or product).
But it sometimes shows many useless "loading" buttons, even though the underlying data doesn't change.
Cleaned up to avoid having : 
- the top section go into loading mode
- the bottom "load more" showing up
> fix: improve page display when the user changes the price or product order

- src/main.js
- src/views/UserSettings.vue
Due to recent language cleanup PR #337 some issues were raised
- UserSettings language dropdown was not showing the current locale name but code
- Refresh or direct URL would default text to English
- Small fix in UserSettings
- Added call of `changeLanguage` before App mount
> fix(i10n): language dropdown and locale load at mount

- src/components/PriceCard.vue
- src/components/ProductCard.vue
- src/components/ProductQuantityChip.vue
- src/i18n/locales/en.json
Currently, if the product quantity info is missing, we simply hide the `ProductQuantityChip` chip + don't calculate the price per kg/L.
But we could also show a "warning" message to nudge users to edit the info in OFF :)
Add a tooltip on hover
> feat(product): if quantity missing, show warning color & tooltip

- src/components/ProductCard.vue
- src/components/ProductCategoriesChip.vue
- src/components/ProductCategoriesDialog.vue
- src/i18n/locales/en.json
In the ProductCard (displayed in the ProductDetail page for instance), we display the CategoriesChip in orange if it's empty (+ tooltip), to nudge users to edit the product.
> feat(product): if categories missing, show warning color & tooltip

- src/components/ProductLabelsChip.vue
- src/components/ProductLabelsDialog.vue
- src/i18n/locales/en.json
Cleanup behavior when the product does not have any labels. It is not as important as categories - #417 - as products may simply not have any labels.
(there is also an idea to simply hide the info if empty, we'll see what the users say in the long run)
> refactor(product): if labels missing, don't show dialog

- src/components/PriceCard.vue
- src/components/ProductBrands.vue
- src/components/ProductCard.vue
- src/components/ProductQuantityChip.vue
- src/i18n/locales/en.json
If the ProductCard (or PriceCard) has no brands, show the chip with a warning color (and a tooltip on hover), instead of hiding it
> feat(product): if brand missing, show warning color & tooltip

- src/components/ProductCard.vue
Hide product code to gain some space
- possible to retrieve it via the OFF / share links
- if asked to be put again by power users, we can add a toggle in the settings in the future
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/1800631f-820a-4f56-a88e-79cd9d473f0f)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/dda4b075-290c-401b-8c73-42c7956d0e7b)|
> refactor(product): hide product code

- src/components/ProductBrands.vue
- src/components/ProductBrandsDialog.vue
- src/i18n/locales/en.json
Some products, have (too) many brands, that clog the ProductCard.
Now, if the brand count is greater than 2, the brands are replaced with a count chip + dialog (like categories & labels)
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/67883263-6a42-43b0-8c9f-136b44286bea)|![Screenshot from 2024-03-09 10-56-38](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/64baad0b-63d9-4346-b132-315210f8c4cb)|
> feat(product): if too many brands, show count & dialog

- src/store.js
- Fix wrong name in store for `favorite_currencies` in get and set functions
> fix(store): wrong name for favorite_currencies

- src/components/PriceDeleteChip.vue
- src/components/PriceDeleteConfirmationDialog.vue
Changes : 
- seperate `PriceDeleteChip` and a new `PriceDeleteConfirmationDialog`
- make the dialog scrollable
> refactor(price): new PriceDeleteConfirmationDialog component

- src/components/Footer.vue
- src/components/OpenFoodFactsLink.vue
In the `OpenFoodFactsLink` component, we currently send all urls to https://world.openfoodfacts.org/
This PR changes the URL prefix depending on the user locale
- example : https://es.openfoodfacts.org/
- if the locale doesn't exist (example : en_gb), it will be redirected to world
> feat(l10n): change OFF url depending on user locale

- src/components/Header.vue
- src/i18n/locales/en.json
Explicit the 'Sign in' icon on larger screens
|breakpoiint|Image|
|---|---|
|xs|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/9f5351c9-9d02-4baf-bc96-c1fa1f1885c0)|
|sm +|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/d06898d0-392f-42d6-8540-be1bde8953f4)|
> refactor(header): show 'Sign in' text on larger screens

- src/components/Header.vue
Explicit the Username on larger screens
|breakpoint|Image|
|---|---|
|xs|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/9b956d2b-50ea-40e9-8ca0-f23b4ea72a60)|
|sm +|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/09f14e0d-c9e3-4dfd-a283-c6254423da94)|
> refactor(header): show Username text on larger screens

- src/components/PriceFooter.vue
- src/components/PriceProof.vue
- src/components/ProofCard.vue
- src/components/ProofDeleteConfirmationDialog.vue
- src/components/ProofEditDialog.vue
- src/components/ProofFooter.vue
- src/components/UserRecentProofsDialog.vue
- src/i18n/locales/en.json
- src/views/AddPriceMultiple.vue
- src/views/ProofDetail.vue
Cleanup & fixes following recent Proof privacy changes (especially #462)
- rename hideProofDelete to hideProofActions
- show proof actions only on dashboard & detail page
- translations
> fix(proofs): cleanup post proof privacy recent changes

- src/components/ProofEditDialog.vue
- src/components/ProofFooter.vue
- src/components/ProofPrivateChip.vue
- src/components/ProofTypeChip.vue
- src/views/AddPriceMultiple.vue
Following #466, we display the proof privacy status. Only for receipts
> feat(proofs): display the proof receipt privacy status in the proof footer

- src/components/PriceCard.vue
- src/components/ProductCard.vue
- src/components/ProductMissingChip.vue
When the product (or the price product) is missing, show a new "error" badge
||Image|
|---|---|
|PriceCard|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6834bd1b-0b8e-4682-9e4e-27c84a2766f1)|
|ProductCard|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/5d9f7db6-97fb-44a6-b2d2-65187831121b)|
> feat: show an error chip if the product is missing

- src/components/ProductOrderMenu.vue
- src/constants.js
- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/LocationDetail.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/UserDetail.vue
Similar to #479
- new `ProductOrderMenu` component
- use in `BrandDetail`, `CategoryDetail`, `ProductList`
- change button style (round)
- rename "order by" to "order"
> refactor: new ProductOrderMenu component

- src/components/FilterMenu.vue
- src/components/OrderMenu.vue
- src/i18n/locales/en.json
- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/LocationDetail.vue
- src/views/LocationList.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/UserDetail.vue
- src/views/UserList.vue
- reduce the size of the Filter & Order menu buttons
- move to one line to reduce space
||before|after|
|---|---|---|
|ProductList|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/bc94a9c1-3d92-452c-ac59-eab5e44c5078)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6658a6a8-1e64-420a-8b3b-59177af0f678)|
|ProductDetail|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/661a96fd-c230-4dd1-950c-ce795b045e82)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/204c9cb3-7aa4-4bae-ac51-d0ce88ee7aa6)|
> refactor: move FilterMenu & OrderMenu on the same line

- src/components/ProofActionMenuButton.vue
- src/components/ProofEditDialog.vue
- src/components/ProofFooter.vue
- src/i18n/locales/en.json
- src/views/AddPriceMultiple.vue
Revert changes in : 
- add price multiple
- edit proof
- proof privacy chip
> refactor: disable allowing a user to set a receipt as private

- src/components/FilterMenu.vue
- src/components/OrderMenu.vue
- src/constants.js
- src/i18n/locales/en.json
- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/ProductList.vue
Following #479, related issue #502
Extend the `FilterMenu`, and add a new filter by source
- source = OFF, OBF, OPFF or OPF
- updates the url
- only available in the `ProductList` page
> feat(products): add new filter by source

- src/components/PriceCard.vue
- src/components/PricePriceRow.vue
Changes on the `PriceCard`
- move price below image
- reduce image size
- show product price count badge
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/20077da3-df21-47df-a37c-3c8437f844ba)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/171ab1cf-6665-4cf8-891a-b58f808d7e18)|
> feat: improve price card (condense, show product price count)

- src/components/OpenFoodFactsAddMenu.vue
- src/components/OpenFoodFactsLink.vue
- src/components/OpenStreetMapLink.vue
- src/components/ProductPriceAddButton.vue
- src/components/ShareButton.vue
- src/views/ProductDetail.vue
Improve the CTA button to add a missing product to OFF
- show a dropdown with all the flavors
- deeplink to the add page
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/8fc40720-4a95-4b29-acf6-45666eb2136a)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6cea19a8-06f8-4b44-b13c-fabbf7b493b2)|
> feat: when a product is not found, improve CTA to add the product to OFF

- src/utils.js
- src/views/ProductDetail.vue
For prices with a `category_tag`, we were using the old categories, and not the new/translated ones
> fix(product detail): fix display and translation of price category name

- src/components/PriceEditDialog.vue
- src/i18n/locales/en.json
> feat(price): allow editing price date

- src/components/PriceAddButton.vue
- src/components/PriceCard.vue
- src/components/ProductCard.vue
- src/views/ProductDetail.vue
- src/views/ProofDetail.vue
- tests/e2e/spec.cy.js
We currently have a bug, where error messages are displayed on the raw product detail page.
- linked to #474, and multiple following fixes / reverts :sweat_smile: 
- now that we have tests it should not happen again :pray: 
I also added a price count badge.
> fix(Product detail): avoid 'Unknown product' message displayed for raw categories

- src/components/LocationCard.vue
Thanks to https://github.com/openfoodfacts/open-prices/pull/294 we now have `Location.osm_tag_key` & `Location.osm_tag_value`.
We can display them in the `LocationCard` as a chip
> feat(Location): display osm_tag in a new chip

- src/components/UserRecentProofsDialog.vue
- src/views/AddPriceMultiple.vue
- Adds a load more button at the bottom of the recent proofs list in the dialog box used when adding prices.
Also, filters the proof type when fetching proofs based on if you're adding receipts or regular price tags.
- 
-
> feat(proof): recent proof dialog: add load more button, filter list depending on receipt or price tag

- .husky/pre-commit
- CONTRIBUTING.md
- package.json
- yarn.lock
Following #586 
Add husky & lint-staged to have linting checks on each commit
> test: setup pre-commit with linting

- src/components/LocationCard.vue
- src/constants.js
- src/services/api.js
- src/utils.js
Following #517
- improve on which Photon keys the filtering is done (to hide non-shops)
- improve location results display (key:value)
- do the same for the location detail card
> fix(location): improve location search result filtering and display

- src/components/PriceAddButton.vue
- src/views/AddPriceSingle.vue
- Solves the missing proof image from https://github.com/openfoodfacts/open-prices-frontend/pull/557 and also inserts the proof created date to the form.
_It uses the date the proof was uploaded, so might not always be the correct date for when the picture was taken_
- 
-
> feat(proof): fetch and insert proof data to 'add single price' page when using 'add the price' button

- src/components/CategoryCard.vue
- src/components/CategoryTagChip.vue
- src/components/PriceCard.vue
- src/i18n/locales/en.json
- src/store.js
- src/utils.js
- src/views/ProductDetail.vue
- src/views/UserSettings.vue
Similar to #559
- new user setting to toggle the display of the product category in the Product Detail page
- new `CategoryCard` & `CategoryTagChip` components
> feat(settings): user setting to display raw product category tag

- src/components/ProductBarcodeNotValidChip.vue
- src/components/ProductCard.vue
- src/i18n/locales/en.json
- src/utils.js
On the `ProductCard`, check if the barcode is valid or not.
https://stackoverflow.com/a/67933747/4293684
|Page|Image|
|---|---|
|Add price|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f464521f-b622-43e1-bec1-454b5f7ba064)|
|Product detail|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/fdade9c0-87db-4f95-891e-17fdd2e560e5)|
> feat(product): new warning if the barcode is not valid

- src/components/PriceInputRow.vue
- src/i18n/locales/en.json
Replace the discount checkbox with a switch
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f80df5b6-4a79-49dc-a20b-418315f77b89)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6da2b3ef-1cad-4212-ac2d-96539650ad0d)|
> refactor(price add): change the ui of the discount toggle (switch instead of checkbox)

- src/components/CurrencyChip.vue
- src/components/ProofDateChip.vue
- src/components/ProofFooter.vue
If available, show the proof date & proof currency in the proof card footer
> feat(proof card): display date & currency in the footer

- src/components/PriceInputRow.vue
- src/components/ProofInputRow.vue
- src/i18n/locales/en.json
- src/services/api.js
- src/views/AddPriceMultiple.vue
- move up `date` & `currency` form fields to the Proof section (`ProofInputRow` created in #632)
- new "Upload" button
- and display the `ProofCard` once it is uploaded (or selected if coming from an existing proof)
|1. Select proof|2. Upload proof|3. Display proof|
|---|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/e4eb0e8d-5a9d-44e7-92c4-7c57df97950d)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/5a2f5bb4-d444-45c0-8164-ae81bc40cd89)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/47da1a42-9bef-4519-81c1-a7ff72712ebb)|
> feat(price add): move date & currency to the proof section

- src/components/PriceAddButton.vue
- src/views/AddPriceMultiple.vue
- src/views/ProofDetail.vue
Since #557 there is a "Add price" button in the proof detail page.
But it was directing users towards the "single price" workflow.
With this change users are now directed towards the "multiple price" workflow.
- fetch existing proof prices and display them in the form ?
> refactor(price add): when coming from the proof detail page, direct users to multiple add form

- src/views/AddPriceHome.vue
- src/views/AddPriceSingle.vue
Disable the single price workflow
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/47cda78e-c57e-4540-9780-0ac64617a49a)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/15ba7a4a-7016-4f79-915a-3031b1c71b13)|
> feat(price add): hide single price add workflow

- src/components/ProofActionMenuButton.vue
- src/components/ProofCard.vue
- src/components/ProofEditDialog.vue
- src/components/ProofFooter.vue
following #462
- cleanup remainings of "proof private" - #506
- start allowing editing proofs (if 0 prices for now)
> refactor(proof edit): cleanup is_public. Allow editing date if no prices

- src/components/ProofDeleteConfirmationDialog.vue
- src/components/ProofEditDialog.vue
- src/components/ProofInputRow.vue
- src/views/UserDashboardProofList.vue
In #378 we started using the store to keep user proofs and avoid fetching them again.
But there regularly some inconsistencies, in particular the proof's `price_count` is important because it currently decides if the proof is editable/deletable.
> refactor(proof store): disable proof store because of inconsistencies

- src/components/CurrencyChip.vue
- src/components/ProductBrands.vue
- src/components/ProofFooter.vue
- src/i18n/locales/en.json
Following #640 we started showing a currency chip in the Proof card footer.
This data is important / mandatory, so show an error if it is missing.
||Image|
|---|---|
|Before|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6013077f-8925-4dbb-a412-17de40e9301a)|
|After|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/1d6940e7-9424-4334-b6bc-5e5d081a5030)|
> refactor(proof card): if currency missing, show chip with error & tooltip

- src/components/PriceCard.vue
Solves a specific case where, when fetching price data, we have their proofs but not their proof's locations.
So when displaying the proof dialog, it showed only the proof's location_id instead of the text.
Found a hack to display it.
Long-term solution : return the proof location object as well ? adds a SQL join...
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f5ec47da-7bef-4871-ac61-9598bdfccb4c)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/d2ef3d13-e43d-40d4-8967-a6db52ef2c1f)|
> fix(proof card): fill in location data from price if missing from proof

- src/services/api.js
Linked with a backend change : https://github.com/openfoodfacts/open-prices/pull/342
On price create, we were sending extra (non-model) fields such as `category` & `product`.
Do some pre-cleaning to avoid it, as it now returns an error
> refactor(API): on create/update, only send needed fields (price, proof)

- .github/workflows/release-please.yml
- src/components/ProofInputRow.vue
- src/components/UserRecentProofsDialog.vue
- src/views/AddPriceMultiple.vue
- responsive : columns & blocks
- hide some buttons until they are useful
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/ce31d3a8-efb7-45bc-97a2-c81883f7a9ce)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/6c072ba5-90f8-4af3-aac6-c8d211a33361)|
> refactor(price add): reorganise a bit the price add workflow

- src/components/ProofEditDialog.vue
- src/components/ProofTypeInputRow.vue
- src/constants.js
- src/views/ProofAddSingle.vue
Allow editing the proof type (note : edit still only allowed for proofs without prices)
New `ProofTypeInputRow` component
> feat(proof edit): allow editing a proof type

- src/components/DateChip.vue
- src/components/PriceCard.vue
- src/components/PriceFooterRow.vue
- src/components/PricePriceRow.vue
- src/components/ProductCard.vue
- src/components/ProofChip.vue
- src/views/AddPriceMultiple.vue
Changes to the `PriceCard`, following the new `DateDetail` page (#675) and allow users to navigate to the dates/month/years.
- moved the price date to the footer
- link to the date detail when clicking on the date chip
- give a bit more space the product image
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/769ce23f-6bf2-4d1a-ab02-fa957957f930)|![image](https://github.com/user-attachments/assets/99923019-91d8-406d-bf41-25434e25723f)|
> refactor(Price card): move price date to footer

- src/components/LocationActionMenuButton.vue
- src/components/LocationCard.vue
- src/components/OpenStreetMapLink.vue
- src/views/LocationDetail.vue
Similar to #696
In the Location card (and Location details), move the "OpenStreetMap link" to a new `LocationActionMenuButton`
> refactor(Location card): new action menu with OSM link

- src/components/OpenFoodFactsLink.vue
- src/components/PriceAddLink.vue
- src/components/ProductActionMenuButton.vue
- src/components/UserActionMenuButton.vue
- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/ProductDetail.vue
- src/views/ProofDetail.vue
Following #698
Move the PriceAdd button to the new ProductActionMenu
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/f0e22476-58b5-4cb9-916f-a400352d8005)|![image](https://github.com/user-attachments/assets/08ec8afa-7730-45da-9ac9-c078ae988d59)|
> refactor(Product card): move PriceAdd action to menu

- src/components/ProofActionMenuButton.vue
- src/views/ProofDetail.vue
Similar to #700
Move the PriceAdd button inside the `ProofActionMenuButton`
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/8deb7aa7-96c0-4f41-9927-6c33dd02a331)|![image](https://github.com/user-attachments/assets/25f0e02c-8f2b-41d1-bc7f-1175db83164f)|
> refactor(Proof card): move PriceAdd action to menu

- src/components/LocationActionMenuButton.vue
- src/views/LocationDetail.vue
Similar to #704 
Move the `ShareLink` button to the `LocationActionMenuButton` (created in #697)
> refactor(Location card): move Share action to menu

- src/components/UserActionMenuButton.vue
- src/views/UserDetail.vue
Similar to #704 
Move the `ShareLink` button to the `UserActionMenuButton` (created in #696)
> refactor(User card): move Share action to menu

- src/components/FilterMenu.vue
- src/constants.js
- src/i18n/locales/en.json
- src/views/UserDashboardProofList.vue
> feat(Dashboard): New filtering menu to hide proofs with prices

- .github/labeler.yml
- ci: Update labeler.yml to V5 syntax
> ci: Update labeler.yml to V5 syntax

- src/components/CountryCard.vue
- src/components/LocationCard.vue
- src/views/CountryCityDetail.vue
- src/views/CountryDetail.vue
- src/views/LocationList.vue
Following the #766 & #771
If the location has `osm_address_country` & `osm_address_city`, then display as chips + links to `CountryDetail` & `CountryCityDetail` pages
> feat(Location card): display Country & City if available

- src/components/ProofActionMenuButton.vue
- similar to #797 (for Price), we add a "Details" action in the `ProofActionMenu`
- we also add a "PROOF" title
> refactor(proofs): add a Proof Action to the details page

- src/components/PriceCountChip.vue
- src/components/UserCard.vue
- src/i18n/locales/en.json
Thanks to new fields in the backend - see https://github.com/openfoodfacts/open-prices/issues/419 - we can display the User's location, product & proof counts
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/96732e14-701e-4da7-8e47-b4668591f496)|![image](https://github.com/user-attachments/assets/007f4dd4-7c5f-43a7-8572-328e67bd3e3f) |
> feat(users): show location, product & proof counts

- src/services/api.js
The current frontend default is to load data by batches of 10.
The backend server allows 100.
For stats purposes, we bump the default page size to 100 (load more prices => show more locations on the map & points on the price chart)
> refactor(api): bump default page_size to 100

- src/utils.js
- src/views/PriceList.vue
Basic custom infinite scroller on the Price list page.
When the page reaches 90%, fetch new data.
- debounce : https://stackoverflow.com/a/75988895/4293684
- calculate scroll percentage : https://stackoverflow.com/a/2387222/4293684
- ` v-infinite-scroll`  didn't work for me
- nor ` infinite-scroller`
> feat(prices): replace Load More with infinite scroll

- src/services/api.js
Photon API allows to restrict the osm_tag returned.
Following a discussion here - https://github.com/openfoodfacts/smooth-app/issues/5568 - we restrict the results to `shop` & `amenity`.
A button/link to offer the user to widen its search if no results found
> refactor(location search): Photon: restrict via API URL on shop & amenity

- src/components/OrderMenu.vue
- src/constants.js
- src/i18n/locales/en.json
- src/views/LocationList.vue
- src/views/ProductList.vue
Foliowing #853. Similar to #856
Add the `OrderMenu` with the 4 counts as choices
> feat(locations): new order menu by counts

- src/i18n/locales/en.json
- src/services/api.js
- src/views/Stats.vue
Thanks to https://github.com/openfoodfacts/open-prices/issues/463
- simplify the Stats page by doing 1 single API call
- show last updated
> refactor(stats): Use new /stats endpoint. Show last updated date

- src/components/Header.vue
- src/i18n/locales/en.json
- src/views/Home.vue
See issue #843 
Improved Home Page
- show basic stats
- show 5 latest prices + button to see more
- Search & Add actions moved to the header (and they remain available in the top-left menu)
- more stats (locations, users)
- center "Latest prices" button
||Before|After|
|---|---|---|
|Desktop|![image](https://github.com/user-attachments/assets/e617ca33-9232-45e1-a759-5f719d2ad9e9)|![image](https://github.com/user-attachments/assets/17960847-8030-4c16-ad44-1abcdc7d504f)|
|Mobile|![image](https://github.com/user-attachments/assets/1327ea70-9aa5-4c31-b208-0fe52fd3147f)|![image](https://github.com/user-attachments/assets/31e3a9d2-7583-40b2-8643-a8c7091d83e9)|
> feat(Home): reorganize home page sections. move buttons to header

- src/views/BrandDetail.vue
- src/views/CategoryDetail.vue
- src/views/CountryCityDetail.vue
- src/views/CountryDetail.vue
- src/views/DateDetail.vue
- src/views/LabelDetail.vue
- src/views/LocationDetail.vue
- src/views/LocationList.vue
- src/views/PriceList.vue
- src/views/ProductDetail.vue
- src/views/ProductList.vue
- src/views/ProofDetail.vue
- src/views/Search.vue
- src/views/UserDashboardPriceList.vue
- src/views/UserDashboardProofList.vue
- src/views/UserDetail.vue
- src/views/UserList.vue
Following a similar change on the Home page - https://github.com/openfoodfacts/open-prices-frontend/commit/c3d04ed4a2ee4489a6972613fbcd8295036ee81c - we generalize the 4 columns on xl screens on every page
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/c990ad65-561e-4b78-9589-e4d3e5f8516c)|![image](https://github.com/user-attachments/assets/59de0450-ba2b-4c30-8dc8-6ea9c5721605)|
> refactor: show 4 columns on xl screens

- src/utils.js
- Make new price show  "Xs" ago or "Xm" ago instead of "2h" ago
| Before | After |
| --- | --- | 
|![before](https://github.com/user-attachments/assets/45107a76-2924-4142-9a20-fd2d067856a4)|![after](https://github.com/user-attachments/assets/db8f8e7a-af43-43a1-9a2a-46e0247f510a)|
- Fixes #877
> fix(utils): relative time display

- src/router.js
See #364 (load the main app at https://prices.openfoodfacts.org)
We'll redirect all upcoming queries with `/app` by removing the prefix
> refactor(router): Add redirect for future users coming from /app

- src/views/UserDashboardPriceList.vue
- src/views/UserDashboardProofList.vue
User Prices
- move Dashboard link down
- remove Share button
User proofs
- fix count
- move Dashboard link down
> refactor(Dashboard): fix Proof count. Cleanup Price & Proof headers

- src/components/ProofActionMenuButton.vue
- src/components/ProofCard.vue
- src/components/ProofChip.vue
- src/i18n/locales/en.json
Thanks to https://github.com/openfoodfacts/open-prices/issues/340 we now have proof image thumbnails.
- we display them instead of the full/slow proof images
- Proof action menu: added a link to view the full-size image
> refactor(Proofs): show image_thumb instead of (full) file image

- src/components/ProofImageInputRow.vue
- src/components/ProofInputRow.vue
Add price form: refactoring to move proof image-related stuff in a dedicated component
> refactor(Add prices): new ProofImageInputRow component

- src/components/StatCard.vue
- src/components/UserActionMenuButton.vue
- src/services/api.js
- src/views/UserDashboard.vue
New user dashboard
- show user card at the top
- load data thanks to https://github.com/openfoodfacts/open-prices/pull/500
- add a link to the user settings in the action menu
- show stats (with CTA to see the full list)
- show latest prices (like home)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/52c7f2d0-b747-48f8-8892-8aa5d3a36292)|![image](https://github.com/user-attachments/assets/e7ed0392-779e-4aff-a034-8668cca59fb8)|
> feat(User dashboard): improve look & feel

- src/components/BarcodeManualInputDialog.vue
- src/components/ProductInputRow.vue
When adding a price, users have the possibility to type the code manually. But sometimes a mistake a make (same for the barcode scanner).
Now, when trying to input the code again, it will be prefilled with the existing value.
> refactor(Price add): Improve barcode manual input by prefilling with current code

- src/store.js
- src/utils.js
- src/views/SignIn.vue
I've noticed that my acces_token always takes the following shape: `<username>__U<uuid>`, even when I use an email as login.
If this is true, maybe parsing this access token, extracting the username and feeding it to the appStore could allow user to still use email as login.
- Fixes #947
This might require some testing, I couldn't find documentation on what the OFF token should look like, so I only have my own experience as data.
> feat(SignIn): parse and use username from access_token on signin, allows usage of emails to login

- src/components/ProofFooterRow.vue
Following #806 where we hide by default the price owner chip (in the Price card) & https://github.com/openfoodfacts/open-prices-frontend/commit/ee4468019fc222af6c96dcb3bc523578500c9bfe (prop to toggle).
Here we do the same but in the Proof card
a bit of privacy
> refactor(Proof card): hide by default the proof owner chip

- src/views/ProofDetail.vue
Similar to #806 (Price detail history section), but in the Proof detail page
- we removed the Proof owner chip in #959, and we display it in the history section instead
- to mimic the Price detail page
- to close #804 ^^
> refactor(Proof detail): add history section at the bottom

- src/components/ProofCard.vue
- src/views/UserDashboardProofList.vue
- Following #924
- Only show proof thumb image in User Dashboard Proof List
- All other pages should display the original proof image, as to not offuscate important details
- Fixes #952
> refactor(ProofCard): Only show proof thumb image in User Dashboard Proof List

- src/i18n/locales/en.json
- src/views/Stats.vue
Following https://github.com/openfoodfacts/open-prices/pull/524 (backend), display 4 new stats : 
- Location count by types OSM & ONLINE
- Proof count by types GDPR_REQUEST & SHOP_IMPORT
> refactor(Stats page): add extra count by location & proof type

- src/components/ProofCard.vue
- src/components/ProofFooterRow.vue
Following #976 some proofs will now have 2 extra metadata.
If the data is available, and if the user is the proof owner, we display them.
> feat(Proof card): show new consumption-related fields in the footer

- .env.local
- .env.prod
- .env.staging
- package.json
- public/manifest.staging.json
- src/constants.js
- use "staging" instead of "preprod"
- new "VITE_OPEN_PRICES_ENV" variable
> ci: rename preprod to staging

- src/components/Header.vue
- src/router.js
Header changes (when logged in)
- remove the user menu dropdown
- clicking on the user icon sends to the dashboard
Drawer (when logged in)
- change Dashboard icon (now same as user in the header)
- add Sign Out button at the bottom
> feat(Header): hide old User settings, move Sign Out to drawer

- src/components/LeafletMap.vue
- src/components/LocationSelectorDialog.vue
- src/utils.js
A few small improvements in the location search dialog:
- show a search hint with examples
- allow searching for "N12208020359" (was already possible to search for "12208020359" thanks to #617)
- improve map zoom when only 1 result is returned
> refactor(Location search): add search hint, improve map zoom for single result

- src/views/Stats.vue
In https://github.com/openfoodfacts/open-prices-frontend/commit/07fa5d847df5f3a9b9700a598ec390dc729bcdf9 we added button links to top prices/products/locations/users pages.
Slight revert and add these links to the existing StatCards (thanks to changes in #939)
Cleaner UI, also avoid padding issues with the buttons on small screens
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/e8918ec7-9beb-4c5b-9012-aee95a5a71f0)|![image](https://github.com/user-attachments/assets/9f03633c-416a-4b88-8704-985f5be9a3ec)|
> refactor(Stats): add links inside StatCard instead of dedicated buttons

- src/components/LoadedCountChip.vue
- src/components/LocationSelectorDialog.vue
- src/constants.js
- src/i18n/locales/en.json
- src/views/Stats.vue
Location selector: new tabs at the top to toggle between OpenStreetMap search & Recent locations.
- to move the recent locations to a dedicated section
- to prepare for a "Online" tab
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/ad62c4b1-c3a7-485a-ba1e-65ad8f3c1f76)|![image](https://github.com/user-attachments/assets/a69674b0-47e2-447e-9858-593575e8ecf9)|
> refactor(Location selector): Add tabs to choose between OSM & Recent

- src/i18n/locales/en.json
- src/views/Settings.vue
Following #1029
Split the 'Display' section, and move some over to a new 'Developer mode'
- 'Display' section was getting too big
- Many apps have a 'Developer mode', these stuff belong there
> refactor(Settings): Move some settings to a new 'Developer mode' section

- src/data/reuses.json
- src/i18n/locales/en.json
- src/router.js
- src/views/Reuses.vue
New page to list reuses.
New `reuses.json` to store the details of each reuse (move this to the backend + API in a v2 ?)
https://github.com/openfoodfacts/open-prices/discussions/562
> feat: new page to list known reuses

- src/components/ProofInputRow.vue
- src/services/api.js
- src/views/ContributionAssistant.vue
Refactoring in api.js
- avoid having to pass all the price/proof parameters when creating/updating the objects
- always filter the input data with the expected body keys
- simplify the code
- make space for a new "source" param
> refactor(API): always filter input data fields before POST

- src/components/ProofInputRow.vue
- src/services/api.js
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
- src/views/ContributionAssistant.vue
Following #1034 & #1025.
A bit of a hack, where we send the user's current page URL on each POST.
To have some stats on where the proofs & prices are created (as we have multiple forms now).
> refactor(API): send the page url on every POST

- src/components/PriceCard.vue
- src/components/ProductCard.vue
- src/components/ProductInputRow.vue
ProductCard: new `hideCategoriesAndLabels` prop
ProductInputRow: use this new prop to reduce a bit the space when finding an existing product
> refactor(ProductCard): new prop to hide categories & labels chip

- src/components/ContributionAssistantDrawCanvas.vue
- src/components/ContributionAssistantPriceFormCard.vue
- src/views/ContributionAssistant.vue
- Display detected barcode below product suggestion, to compare
- Show more cols on larger screens
- Hide "price per" input when barcode is selected
- Allow for price removal at the cleanup step, with a trashcan icon
- Add a 4th step: Summary, with progress bars tracking proof and price uploads and navigation buttons to user profile, added proof or to go back to the image selection step
- #1025
> refactor(ContributionAssistant): More UX tweaks following feedback

- src/views/ContributionAssistant.vue
- Simple PR in reference to @raphodn suggestion in #1039
- If gemini detects something that looks like a barcode (more than 10 characters), it's better to suggest the barcode mode instead of the category one
> refactor(ContributionAssistant): use barcode mode when codes look credible

- src/components/BarcodeManualInputDialog.vue
- src/components/PriceEditDialog.vue
- src/components/ProofEditDialog.vue
- src/components/ProofInputRow.vue
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
- src/views/ProofAddMultiple.vue
- src/views/ProofAddSingle.vue
After some extensive price-adding with Justin this weekend, first of a few PRs to sightly improve the UI.
Submit buttons : 
- always right-align (people hold their phones with their right hand... though I'm left-handed ^^)
- avoid confusion between Submit & Done buttons
|---|---|---|
|Add multiple prices|![image](https://github.com/user-attachments/assets/4e49b5af-998e-4b55-83ba-0f1e386a43a2)|![image](https://github.com/user-attachments/assets/b3e89309-a9bb-4628-a70c-1dc7ab740260)|
> refactor(UI): right-align all submit buttons. change color of Done buttons

- src/views/AddPriceMultiple.vue
After adding many prices for a given proof, the user needs to scroll.
To be tested, can be reverted if not intuitive after all...
> refactor(UI): On new price, scroll UI to the form

- src/components/PriceAlreadyUploadedListCard.vue
Following https://github.com/openfoodfacts/open-prices-frontend/commit/382cbff21d364b7aa109749c2f9674287d0e127e (new PriceAlreadyUploadedListCard component)
We start adding some useful info in the footer of the card
> refactor(Price add): show count & sum of already added prices (receipts)

- src/components/PriceAlreadyUploadedListCard.vue
- src/components/ProofFooterRow.vue
- src/components/ProofReceiptPriceCountChip.vue
- src/components/ProofReceiptPriceTotalChip.vue
Following #1074 & #1075
We add the proof extra (optional) personal fields as extra context (only if available) (only for receipt proofs)
|Without receipt extra personal fields|With receipt extra personal fields|
|---|---|
|![image](https://github.com/user-attachments/assets/49e57920-e13d-4a22-8fc2-0861e255f242)|![Screenshot from 2024-12-02 23-51-47](https://github.com/user-attachments/assets/9a22bf78-6b6b-48c4-b103-8c68bd27bc06)|
> refactor(Price add): show receipt personal data in already added prices footer

- src/assets/main.css
- src/components/ProofTypeInputRow.vue
Linked to #1085: start working on revamping/simplifying the price add form
Changes on the Proof type selector
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/350b65ec-9d79-43b5-bc3b-42af3b69b23c)|![image](https://github.com/user-attachments/assets/c7430185-3974-4651-86f7-e135a3d095ca)|
> refactor(Price add): new Proof type form input (single button)

- src/assets/main.css
- src/components/ProofTypeInputRow.vue
Linked to #1085: start working on revamping/simplifying the price add form
Changes on the Proof type selector. Revert changes done in #1096 (not a fan after all of the buttons)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/350b65ec-9d79-43b5-bc3b-42af3b69b23c)|![image](https://github.com/user-attachments/assets/0099b21d-ae99-4436-b388-6be23d44c842)|
> refactor(Price add): new Proof type form input (revert back to chips)

- src/views/ContributionAssistant.vue
- See title
- Fix #1083
- Linting is expected to fail since the ContributionAssistant still has hardcoded text, without translation support. But that's another issue.
> fix(ContributionAssitant): strip whitespaces from gemini detected barcodes

- src/views/ContributionAssistant.vue
- In some rare cases, gemini sets the `labels_tags` to organic for images with barcodes.
- This is not supported by the API: `labels_tags [ "Should not be set if 'product_code' is filled" ]`
- This PR removes the field before calling the API
> fix(ContributionAssistant): remove labels_tags param when sending barcodes

- src/components/BarcodeManualInputDialog.vue
- src/components/BarcodeScannerDialog.vue
- src/components/LocationSelectorDialog.vue
- src/components/ProductInputRow.vue
Following #1102 where we merged the barcode scan & manual input in 1 single dialog.
Changes:
- minimum dialog height
- show product result on search + user needs to select the product for confirmation
Following feedback in #1085
> refactor(Price add): On barcode manual input, show result confirmation before send

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/views/AddPriceMultiple.vue
- src/views/AddPriceSingle.vue
Price add form:
- Category mode: reduce spacing between fields & "Organic" checkbox
- reduce spacing between price fields & "Discount" checkbox (was a switch before)
- remove "Price" label
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/593f6ee7-e5a1-4025-a17c-630116ac35fc)|![image](https://github.com/user-attachments/assets/00e60bb0-4816-445d-b1ad-4fbe3840d4f6)|
|![image](https://github.com/user-attachments/assets/f578d693-7f51-4d9c-8360-06d510c7f061)|![image](https://github.com/user-attachments/assets/cf9b7df5-8135-49de-878b-98e236dcfe74)|
> refactor(Price add): gain some space near the product & price checkboxes

- src/components/ContributionAssistantDrawCanvas.vue
- src/views/ContributionAssistant.vue
- Following the new ml detection of price tags bounding boxes https://github.com/openfoodfacts/open-prices/pull/614
- This PR uses this new result to speed up the cropping step
After adding a proof, an info message is shown.
Once the bounding boxes are retrieved, images are automatically cropped. Users can still remove or add crops.
The assistant tries to fetch bounding boxes twice (using single proof api).
- The first time right after uploading the proof (useful for proof already uploaded beforehand)
- If that fails, a second fetch is done 5 seconds later, giving time for ml to execute
If both tries fail, the following message is shown to the user
> feat(ContributionAssistant): Add support for automatic label detection

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/views/ContributionAssistant.vue
- src/views/PriceAddMultiple.vue
- src/views/PriceAddSingle.vue
Stop duplicating the price_per selector.
Move it to the `PriceInputRow` component.
Impact on `PriceAddSingle`, `PriceAddMultiple` & `ContributionAssistant` pages
> refactor(Price add): move price_per selector in PriceInputRow

- src/views/UserDashboardPriceList.vue
Following https://github.com/openfoodfacts/open-prices-frontend/commit/906ae20b0a74fbeff21b4b8a717a57f6852b1792 (frontend: adding a new price type filter option in `FilterMenu`) and https://github.com/openfoodfacts/open-prices/commit/fed321494536caf4fa40715497b3b8c4de3d168a (backend: allowing to filter prices by `type`)
We can now add this type filter on the User price list page.
> refactor(User dashboard): Prices: add new filter by type (Barcode or Category)

- src/components/BarcodeScannerDialog.vue
- src/components/LocationSelectorDialog.vue
- src/i18n/locales/en.json
- src/store.js
- src/views/Settings.vue
Following #1095 where we have a single "Find your location" modal with 3 tabs (Recent, Physical & Online).
New settings to allow choosing the default tab.
Some users want to select their recent shop by default.
> feat(Settings): new Location selector default mode settings (recent, physical or online)

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/ProofImageCropped.vue
- src/views/PriceValidatorAssistant.vue
Following #1145
Fixes image display (cropped price tag)
> fix(Price Validation Assistant): fix image display

- src/components/ContributionAssistantPriceFormCard.vue
- src/i18n/locales/en.json
- src/views/ContributionAssistant.vue
- Handles product_name dectection from AI (currently Gemini).
- Display it as an extra form field in the UI, to allow users to correct before upload.
- https://github.com/openfoodfacts/open-prices-frontend/issues/1078
- Backend PR: https://github.com/openfoodfacts/open-prices/pull/646
> feat(ContributionAssistant): add support for product name gemini detection

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/ProofChip.vue
- src/components/ProofFooterRow.vue
In the ProofFooterRow component, allow displaying the ProofChip #inception
To use in the Price Validation Assistant, and allow users to display the full proof (for context)
||Image|
|---|---|
|Before|![image](https://github.com/user-attachments/assets/509cc4da-86c3-4cfa-8253-0fa4c50eb48d)|
|After|![image](https://github.com/user-attachments/assets/6969a389-564b-4fe6-9bc2-449b29b2674d)|
> refactor(Price Validation Assistant): display the ProofChip in the ProofFooter

- src/components/ProofCard.vue
- src/components/ProofUploadCard.vue
- src/views/ContributionAssistant.vue
- src/views/PriceAddMultiple.vue
- src/views/PriceAddSingle.vue
- src/views/ProofAddMultiple.vue
- src/views/ProofAddSingle.vue
Following #1167 
ProofInputRow: rename to ProofUploadCard (to integrate the header & the footer (upload action))
- refactor its usage in different pages (ProofAddSingle, ProofAddMultiple, PriceAddSingle, PriceAddMultiple, ContributionAssistant)
- don't add an overlay after upload (but keep the green border and checkmark !)
||Before|After|
|---|---|---|
|Proof form|![image](https://github.com/user-attachments/assets/0bd553c9-057b-4a7b-be5f-f1b2c8c18682)|![image](https://github.com/user-attachments/assets/0ae0175f-d64a-4907-914e-9f3ee6ef5cb5)|
|Proof selected|![image](https://github.com/user-attachments/assets/d8c60232-79aa-4134-bf88-71dcbb083a64)|![image](https://github.com/user-attachments/assets/d98e9496-b671-45ea-9fc0-d348a6b5eb7f)|
> refactor(Proof upload): rename & upgrade ProofInputRow to ProofUploadCard

- src/components/ContributionAssistantDrawCanvas.vue
- src/components/ContributionAssistantPriceFormCard.vue
- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
- src/services/api.js
- src/views/ContributionAssistant.vue
- The contribution assistant now reads (as input), creates (after drawing) and updates price tags (after price creation)
- When no new price tags are drawn, this significantly improves the speed of the contribution assistant for existing proofs, since it no longer requires waiting for gemini. If new price tags are drawn, we still have to wait for backend processing.
- It also supports skipping the proof upload step when a query parameter contains proofs_ids to handle, e.g: `/experiments/contribution-assistant?proofs=[1512,1513]`
- After uploading the prices, users can press the new "Next Proof" button to go back and handle the next proof_id in params.
Example, starting from a not yet implemented multiple proof upload CTA
https://github.com/user-attachments/assets/517d535f-8283-42f3-957d-94 …
> refactor(ContributionAssistant): Full integration with price tag data

- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
- src/views/ProofAddMultiple.vue
Following #1043 & #1168
Changes on the Multiple proof upload page:
- restrict to only PRICE_TAG
- add a warning/info message (reminder to upload proofs with the same location + date)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/62b5a260-39f1-45c5-8f58-8282db956cfd)|![image](https://github.com/user-attachments/assets/421a5e41-07cc-4c7f-abad-74359826ebf3)|
> refactor(Multiple proof add): skip type input. Add warning message

- src/views/PriceValidatorAssistant.vue
Thanks to a new Proof.ready_for_price_tag_validation field in the backend - https://github.com/openfoodfacts/open-prices/pull/656.
We can now restrict displayed PriceTags to only a subset of Proofs.
We consider that proofs added via the "normal" workflow (Price add multiple) will have their prices added normally.
But proofs added via the dedicated "proof upload" pages will be assistant-only for price addition.
This is a v1. To be discussed / improved.
> refactor(Price Validation Assistant): filter only on proofs ready (uploaded via Proof add pages)

- CONTRIBUTING.md
A section "Help with translating" has been added to the [CONTRIBUTING.md](https://github.com/openfoodfacts/open-prices-frontend/blob/master/CONTRIBUTING.md) manual, as suggested by @raphodn at https://github.com/openfoodfacts/open-prices-frontend/pull/1178#issuecomment-2563141000
_none_
_none_
_none_
> docs: add section & link to translation platform (crowdin)

- .github/workflows/github-projects.yml
ci: add metrics and matomo to the metrics project
- uses: actions/add-to-project@main
with:
project-url: https://github.com/orgs/openfoodfacts/projects/84 # Add issue to the Metrics project
github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
labeled: matomo
label-operator: OR
> ci: add matomo to the metrics project

- src/components/ContributionAssistantDrawCanvas.vue
- src/components/ContributionAssistantPriceFormCard.vue
- src/i18n/locales/en.json
- src/views/ContributionAssistant.vue
Following @raphael0202 feedback  (translated, simplified):
Fixed in https://github.com/openfoodfacts/open-prices-frontend/commit/012b83ff4a07433df436b6a5f4e36c4e21e9927c
Status and price_id are no longer ignored, Cleanup step now contains a second list of prices, below the first one, with unmodifiable (disabled) already added prices. These prices are ignored in further steps. (Note that the content is still showing Gemini predictions, now the actual created price, which might be a bit misleading)
Could be happening when max values were greater than min values, e.g. a bouding box drawn from bottom to top. Fixed.
Not implemented for now. I want to avoid the creation of invalid price tags because of user errors while drawing boxes. Moreover, the price tag creation API takes up to 3 seconds …
> refactor(ContributionAssistant): More pricetags integrations

- src/services/api.js
Following #1035
Now send the app page via the `app_page` param (instead of hacking the `app_version` param)
> refactor(API): send the page url on every POST via the app_page param

- src/components/ContributionAssistantPriceFormCard.vue
Better differentiate the "Error" & "Unreadable" actions
- error = bad cropping from the AI
- unreadable = good cropping but unreadable by a human
||Desktop|Mobile|
|---|---|---|
|Before|![image](https://github.com/user-attachments/assets/e730184e-223f-4fb1-9b88-e6b352d32a9f)|![image](https://github.com/user-attachments/assets/65e84ca5-d2db-4f5f-a719-a067c50ce7ab)|
|After|![image](https://github.com/user-attachments/assets/50e998b7-77bf-414d-a0d3-79e14acd1eca)|![image](https://github.com/user-attachments/assets/5217e86b-5005-41ef-a03d-82209c89082f)|
> refactor(Price tags): add icons next to Error & Unreadable actions

- src/components/BarcodeManualInputDialog.vue
- src/components/BarcodeScannerDialog.vue
- src/components/LocationSelectorDialog.vue
- src/components/PriceDeleteConfirmationDialog.vue
- src/components/PriceEditDialog.vue
- src/components/ProofDeleteConfirmationDialog.vue
- src/components/ProofEditDialog.vue
- src/components/UserRecentProofsDialog.vue
Make all "action" dialogs the same height & width
- mobile: full-screen
- other screens: 80%
Gain some space on mobile.
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/def01a71-b674-4ac9-8036-aa3de6fb01ba)|![image](https://github.com/user-attachments/assets/c9249bac-d167-4996-a13c-38dedf4c27f9)|
|![image](https://github.com/user-attachments/assets/ad1907e5-bcaf-4397-9c96-e47a293dd771)|![image](https://github.com/user-attachments/assets/c7af09b5-2622-4291-934c-9b442ef3c522)|
> refactor(Dialogs): full height & width on mobile

- src/components/BarcodeScannerDialog.vue
- src/components/ContributionAssistantPriceFormCard.vue
- src/components/ProductInputRow.vue
- src/components/ProofImageCropped.vue
When validating prices, and fixing the barcode, we now display the cropped image :tada: 
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/694432e1-8714-4011-b0be-5b6f73c68523)|![image](https://github.com/user-attachments/assets/b17ed233-b9e1-4c7a-be08-0af80b1f4578)|
> refactor(Barcode scanner): display price tag cropped image if available

- src/components/ProofActionMenuButton.vue
- src/components/ProofFooterRow.vue
- src/views/ProofList.vue
Following #1118 we now made it easy to view all proofs to everyone.
This PR adds the bottom-right menu to all proofs (but actions are limited if not the owner)
/proofs page
|Before|After (not proof owner)|After (proof owner)
|---|---|---|
|![image](https://github.com/user-attachments/assets/76489e9b-30f4-4b93-b8f8-d26f0ac64438)|![image](https://github.com/user-attachments/assets/bc85dd20-f24c-4198-92fd-c428344c5b8b)|![image](https://github.com/user-attachments/assets/edbee5ea-a951-4214-bac2-21f635f5e549)|
> refactor(Proofs): display the proof action menu to everyone

- src/utils.js
- src/views/ContributionAssistant.vue
- src/views/PriceValidatorAssistant.vue
Some quick rules to cleanup the barcode string returned by the prediction.
- keep only digits
- remove leading 0s
- special rule for Carrefour (linked to https://github.com/openfoodfacts/open-prices/pull/660)
- also, valid barcodes start at 8 (EAN8)
To increase product matching
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/a4bdee08-0cc5-43ab-9bb1-9f499c0d8b35)|![image](https://github.com/user-attachments/assets/c98f8e7d-3ff7-4887-bef8-3ebbbad13459)|
> refactor(Assistants): barcode pre-cleaning rules to improve matching

- src/components/ProofImageInputRow.vue
- src/components/UserRecentProofsDialog.vue
Improve the UserRecentProofsDialog with a new subheader containing info & filters
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/07f78298-aa1e-424c-8816-c7ac27d191fa)|![image](https://github.com/user-attachments/assets/d08c3acc-c292-4951-a6fc-79dbd6dedced)|
> feat(User recent proofs): Add proof filters in dialog header

- src/components/ProductInputRow.vue
- src/utils.js
Following #1215 (and similar to #275 & #322)
- we now have the translated labels
- we can display the corresponding origin list depending on the user locale
example with the French locale (Organic -> Bio)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/3eebe445-abbc-4747-8342-4278e29f210a)|![image](https://github.com/user-attachments/assets/ff13fc4d-5583-409e-be37-b79dcb57b830)|
> feat(l10n): translate label list in price add form depending on user locale

- src/components/PriceLabels.vue
- src/utils.js
Following #1215 & #1216
Translate price label chip depending on user locale
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/f600c5b6-9689-4f12-9c1f-57cee9f45a49)|![image](https://github.com/user-attachments/assets/a70bb701-5b6c-40cc-b0ef-fec936554cbc)|
> refactor(Price label chip): translate chip content depending on user locale

- src/components/PriceOrigins.vue
Following #321 & #322
Similar to #1217
Translate price origin chip depending on user locale
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/32cd42bf-6395-4520-9ef8-10096c7955f5)|![image](https://github.com/user-attachments/assets/e6aa99b7-2613-4c40-89a7-c6491aab0500)|
> refactor(Price origin chip): translate chip content depending on user locale

- src/components/PriceActionMenuButton.vue
In the Price Card action menu, show a new "Proof" section with a link to the proof details.
Visible for everyone.
> refactor(Price card): Add action to proof detail page

- src/components/ContributionAssistantLabelList.vue
- src/components/ContributionAssistantPriceFormCard.vue
Contribution assistant: small improvements on the label step
- move "Source" chip in a dedicated section to add margin with label image
- hide "Delete" button if label already has a linked price
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/04468222-db60-49f6-b8cf-94d536c880d9)|![image](https://github.com/user-attachments/assets/fdd1443b-a573-4ad7-80cb-beaa112c6729)|
> refactor(Contribution Assistant): make labels linked to prices readonly

- src/components/ContributionAssistantPriceFormCard.vue
- src/views/ContributionAssistant.vue
Contribution assistant: small improvements on the cleanup step
- hide the price tag actions for prices already added
(a better alternative would be to display only the image + price card (not the price form))
- add a bit of padding above the title
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/6abdcb89-ef16-477e-9a09-157a80f406e0)|![image](https://github.com/user-attachments/assets/24687276-2832-455b-9284-dc9274950c98)|
> refactor(Contribution Assistant): cleanup: small improvements for prices already added

- src/views/ContributionAssistant.vue
Contribution assistant: small improvements on the label step (similar to #1222)
- show Proof footer details
To give context (number of prices already added, location, date...)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/18ce7eee-b0d4-4cdf-be6f-abbdcd151519)|![image](https://github.com/user-attachments/assets/d4768f90-c3ab-414a-b4a2-24586d298291)|
> refactor(Contribution Assistant): add proof footer details below canvas image

- src/views/PriceValidatorAssistant.vue
2 small changes in the Price Validation Assistant inner working:
- load less prices (to speed up display)
- fix a bug where a user would validate prices, they would be removed, and the infinite scroll would not be triggered. preload prices instead in the background.
> refactor(Price Validation Assistant): load less prices, but more often

- src/components/ProofUploadCard.vue
- src/views/ProofAddMultiple.vue
Currently, if a user uploads many proofs, the "Done" button shows up starting from the 1st proof uploaded.
This PR fixes the behavior, and show the "Done" button only when all the proofs have been successfully uploaded.
> fix(Proof add multiple): show done button only when ALL proofs have been uploaded

- src/utils.js
- src/views/PriceValidationAssistant.vue
When fetching new price tags, and if the user had at the same time proofs that are being processed, there were cases of duplicate price tags popping up.
Here we add a filter on the price tag creation date. When starting a PVA "session", only price tags already generated will show up.
Up to the user to refresh the whole page if he wants to load the latest generated price tags.
> fix(Price Validation Assistant): avoid duplicate prices tags during pagination

- src/views/PriceValidationAssistant.vue
To avoid errors when displaying price tags to validate, only display price tags that have a prediction.
When a proof is JUST uploaded, it can happen that the prediction has not had time to run, resulting in an error loading the PVA page.
> fix(Price Validation Assistant): only show price tags with a prediction

- src/components/Breadcrumbs.vue
- src/constants.js
- src/views/Home.vue
Tweak a bit the Breadcrumb style to bette display it at the top of the web pages.
- same top & bottom padding
- remove left & right padding
- homogenize with the home page title
Note : will need an extra PR to improve the "middle" content padding (stats & filters row)
|---|---|---|
|Settings|![image](https://github.com/user-attachments/assets/e968f84b-ba88-4cec-9f17-b195b3b62d3d)|![image](https://github.com/user-attachments/assets/ac2a5977-933e-4033-90a5-963cc76cc338)|
|PVA|![image](https://github.com/user-attachments/assets/43562a04-2995-4d8c-ba42-04ba094386c7)|![image](https://github.com/user-attachments/assets/0865c94c-1c43-4929-807f-d79e811da571)|
|Dashboard > My proofs|![image](https://github.com/user-attachments/assets/1dc0e0a6-671b-438e-bfe2-ccf5bb924462)|![image …
> refactor(Breadcrumbs): homogenize display and padding (better)

- src/components/ProofImageInputRow.vue
Change how we display the selected images
- give them more room
- move them under the form button
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/593dc6ac-2aa2-4651-99e9-f8d211d3a445)|![image](https://github.com/user-attachments/assets/2bf1a2c2-031c-4f90-9e4d-b6a0a6b965df)|
> refactor(Proof upload): better display selected images (row & cols)

- src/components/PriceCard.vue
- src/components/PriceFooterRow.vue
In #1158 we started showing in some places the Proof chip in the Proof footer row.
So users are getting used to seeing the Proof chip at the far left.
But in the Price footer the proof is somewhere on the right.
This PR homogenizes this by moving the Proof chip in the Price footer row to the far left as well.
This also gives/shows a bit more importance to proofs (over the rest of the metadata).
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/b8b14edd-fbc4-40e5-ab5e-d3596fad5ef0)|![image](https://github.com/user-attachments/assets/6dd6d27d-59fd-4d24-897c-d8209c94b033)|
> refactor(Price card): Move the proof chip to the left (first)

- src/components/BarcodeScannerDialog.vue
- src/components/ChallengeTakePicturesCard.vue
- src/components/ChallengeValidateCard.vue
- src/components/ContributionAssistantPriceFormCard.vue
- src/components/LocationSelectorDialog.vue
- src/components/PriceEditDialog.vue
- src/components/ProofEditDialog.vue
- src/components/ProofUploadCard.vue
- src/views/ContributionAssistant.vue
- src/views/PriceAddMultiple.vue
- src/views/PriceAddSingle.vue
- src/views/ProofAddMultiple.vue
- src/views/ProofAddSingle.vue
- src/views/Search.vue
- src/views/Settings.vue
- src/views/UserSettings.vue
Following #1268
Change most of the green (success) CTAs to the new OFF color (primary).
Success color is kept for success messages/notifications/forms (vs error).
|-|-|-|
|Proof add multiple|![image](https://github.com/user-attachments/assets/fa5df09b-4153-49f6-af8b-6376dec888d5)|![image](https://github.com/user-attachments/assets/4fb28488-3c85-431e-9b3e-c943c4d21601)|
|Settings|![image](https://github.com/user-attachments/assets/d88fc3bb-d296-4ff2-b4ad-081b71bce72e)|![image](https://github.com/user-attachments/assets/f63107eb-6e00-44f1-b801-484ae6b6940d)|
> feat(Theme): change most CTA button colors to primary (instead of success)

- src/components/ChallengeTakePicturesCard.vue
- src/components/ChallengeValidateCard.vue
- src/components/PriceDeleteConfirmationDialog.vue
- src/components/PriceEditDialog.vue
- src/components/ProofDeleteConfirmationDialog.vue
- src/components/ProofEditDialog.vue
- src/components/ProofUploadCard.vue
- src/views/PriceAddMultiple.vue
- src/views/ProofAddMultiple.vue
- src/views/ProofAddSingle.vue
On mobile, transform CTAs into full-width block buttons
|-|-|--|
|Proof add multiple|![image](https://github.com/user-attachments/assets/086fd8b5-0c04-4145-bbee-f8dc9783f8c8)|![image](https://github.com/user-attachments/assets/2e987285-5dd9-4ed5-9da1-0b58474298d5)|
|Proof add multiple : done|![image](https://github.com/user-attachments/assets/d07c1f16-fb75-42c6-889a-8bcf329fe3f2)|![image](https://github.com/user-attachments/assets/39914272-e6b8-41b9-87c3-6aeae9e97c20)|
> feat(Mobile): have full-width (block) CTAs on mobile

- src/components/PriceAlreadyUploadedListCard.vue
- src/components/PriceInputRow.vue
- src/components/PricePriceRow.vue
Following #1128 we display the "quantity bought' when adding prices for a receipt.
But sometimes (for "category" prices especially), we buy only a given quantity of the product, so a decimal should be allowed (500 g = 0,5 kg for instance).
> fix(Price add): Allow 'quantity bought' field to be decimal

- src/router.js
- src/views/SignIn.vue
Currently:
- When users try to access a page that requires login, they are redirected to the sign-in page
- After signing in, they are redirected to their dashboard
With this PR:
- We keep track of the page they wanted to access
- After signing in, they are redirected to said page
- Users that pressed the regular sign in button are still sent to their dashboard
> feat(SignIn): proper redirect when sign-in is required

- src/components/ProofChip.vue
- src/components/ProofFooterRow.vue
Give more info to the user by adding a label next to the icon.
Hidden by default, will be displayed in the `ConributionAssistantPriceFormCard` component
||Image|
|-|-|
|Before|![image](https://github.com/user-attachments/assets/2e45af2f-76e3-49c6-aa1c-ec4361ce8d98)|
|After|![image](https://github.com/user-attachments/assets/b30e80c8-6dcc-49be-b6ed-fdc75612c09e)|
> refactor(Proof chip): new withLabel prop to display the label next to the icon

- src/components/PriceCard.vue
- src/components/PriceInputRow.vue
- src/components/PricePriceRow.vue
- src/components/ProductCard.vue
Changes to the `PriceInputRow` component : new "mode" prop.
If set to `Display`, then use the `PricePriceRow` component to display the price data.
|mode "Edit"|mode "Display"|
|--|--|
|![Screenshot from 2025-01-20 01-38-40](https://github.com/user-attachments/assets/439fef54-19b4-469d-a255-82bfff821332)|![image](https://github.com/user-attachments/assets/58a341d1-14aa-4b75-a2e8-c41879a53897)|
> refactor(Price input row): new 'mode' prop to display the data in readonly

- src/components/ContributionAssistantPriceFormCard.vue
- src/i18n/locales/en.json
Following #1290 & #1291.
We now display Price tags as "readonly" by default, with a new "Fix" button to toggle to edit mode.
|mode "Display" (default)|mode "Edit"|
|-|-|
|![image](https://github.com/user-attachments/assets/82500ba6-dc81-4278-8aed-f0efc00a3233)|![image](https://github.com/user-attachments/assets/11cbbb46-b0ef-4ee1-a6f2-d064848e69db)|
> refactor(Price tag): move Fix button to toggle Product & Price modes

- src/components/ProductMissingChip.vue
- src/views/ContributionAssistant.vue
- src/views/LocationDetail.vue
- src/views/PriceAddMultiple.vue
- src/views/ProductDetail.vue
Remove the `mdi-alert` everywhere in the app.
- Product missing: the chip is already red, no need to add an extra info
- Elsewhere: use the default `v-alert` icon
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/f55a4213-fa05-4bad-b630-1e91cc12e2af)|![image](https://github.com/user-attachments/assets/10d72f64-03ea-4c65-b4a8-4b3c34b4a3b2)|
> refactor(Product missing): remove warning icon to scare less users

- src/components/PriceCategoryChip.vue
- src/components/ProductInputRow.vue
Following changes in #1291 we can now display the price's product data as readonly.
But there was an issue when displaying the `category_tag` label (for a raw product price), we were missing a translation mecanism (similar to the existing `PriceOrigins` & `PriceLabels` components).
Fixes this by creating a new `PriceCategoryChip`
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/4785a530-3ca0-44b0-86f7-7ead2b23ffbb)|![image](https://github.com/user-attachments/assets/6a9de20e-36bb-4235-a67d-3768ac44888a)|
Todo in the future: 
- improve `PriceOrigins` & `PriceLabels` to avoid having the v-if at the top
- rename `PriceOrigins` & `PriceLabels` to add "Chip" in their name
> refactor(Product input row): new PriceCategoryChip to display the category_tag localized

- src/components/FilterMenu.vue
- src/constants.js
- src/i18n/locales/en.json
- src/views/PriceValidationAssistant.vue
Price Validation Assistant: 
- allow any user to validate any price tag (not just the ones coming from owned proofs)
- add a filter to toggle to only price tags coming from owned proofs
|Before|After|
|--|--|
|![image](https://github.com/user-attachments/assets/fb6bbfd5-9f42-4afb-be04-0b61b2510d62)|![image](https://github.com/user-attachments/assets/8771d4f5-0ca3-455e-8b8d-29a6e314709c)|
> feat(Price Validation Assistant): open price validation to all proofs (not just owned)

- src/components/ProofActionMenuButton.vue
- src/components/ProofImageInputRow.vue
- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
We recently introduced the word "Picture" to talk about Proofs.
To avoid having 3 terms - Proofs, Images, Pictures - we replace "Image" with "Picture".
> refactor(Proofs): wording: replace 'Image' with 'Picture'

- src/components/ChallengeBanner.vue
- src/i18n/locales/en.json
- src/views/Home.vue
Advertise the challenge on the home page.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/5d810909-050c-4531-b077-e0dc16028ede)|![image](https://github.com/user-attachments/assets/d0210f8f-5b66-4d9a-b888-fe2424662c84)|
> feat(Challenge): show simple banner on the home page

- src/components/ContributionAssistantPriceFormCard.vue
- src/views/ContributionAssistant.vue
- src/views/PriceValidationAssistant.vue
Sometimes price tag cards next to each other don't have the same content, and are misaligned.
Add flex to re-align.
||Image|
|-|-|
|Before|![image](https://github.com/user-attachments/assets/27ffebea-c257-4c96-91f2-da0e615588f9)|
|After|![image](https://github.com/user-attachments/assets/4ca83ee7-423b-4ec8-8cd3-45d71ce5e5c4)|
> fix(Price tag): fix price tag vertical responsiveness

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/constants.js
- src/i18n/locales/en.json
- src/store.js
- src/views/Settings.vue
Following the new 'Fix' button in #1292
Allow expert users to have the "price edit form" as the default display.
New settings
> refactor(Price validation): add a new settings to display the price edit form by default

- src/components/ChallengeTakePicturesCard.vue
- src/components/ChallengeValidateCard.vue
Small tweaks on the current challenge page instruction cards:
- title: ~add icon on the left~, add divider
- move stats at the bottom
|Before|Intermediate (with icons)|After (without icons)|
|-|-|-|
|![image](https://github.com/user-attachments/assets/e82ab47f-1f9f-4ac8-b93a-ffbcd3952a41)|![image](https://github.com/user-attachments/assets/1533bf7c-ba62-4903-907a-07206167851b)|![image](https://github.com/user-attachments/assets/0aab28df-09b9-4458-b57a-bc1b015d1852)|
> refactor(CommunityChallenge): reorganise a bit the 2 instruction cards (move stats at the bottom, add divider below title)

- src/components/ProofImageInputRow.vue
Sometimes users select many images, but want to remove 1 or 2. 
Instead of having to re-select them all, allow removing them individually
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/e3cfd7bf-431d-4678-bdaf-a49b8d3a9987)|![image](https://github.com/user-attachments/assets/b47bccdf-cc77-487f-93b4-6a6ff8acd6fc)|
> refactor(Proof upload): allow deleting the picture(s) selected

- src/components/UserActionMenuButton.vue
- src/components/UserCard.vue
- src/views/UserDetail.vue
Changes thanks to https://github.com/openfoodfacts/open-prices/pull/689
Allows to display all of the user's stats in the user card at the top (same stats as the list view).
Also made the "proof count chip" cliquable (and removed the link in the action menu, introduced in #1256)
> refactor(User detail): fetch full user object from backend

- src/assets/main.css
- src/components/ProofMetadataInputRow.vue
Revamp the proof input fields
- outlined
- label at the top
[|Before|After|
|-|-|-|
|Multiple proofs|![image](https://github.com/user-attachments/assets/75a53884-8a08-4033-98fe-981d42874c0d)|![Screenshot from 2025-01-26 11-11-36](https://github.com/user-attachments/assets/1c87a4f3-d42c-45a7-84b3-e32d1348143e)|
|Receipt|![image](https://github.com/user-attachments/assets/70eb577d-58f7-4999-a266-7bb7e3970e7a)|![image](https://github.com/user-attachments/assets/1bccb309-24f8-4048-8de8-9b4b52b57123)|
> refactor(Proof add): change look & feel of input fields

- src/components/ProofMetadataInputRow.vue
Following the input field revamp in #1329
We now have room to add a help icon. And inform users on how to change their currency config.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/ce8f6048-5199-4b8e-bf7d-db81244a7a17)|![image](https://github.com/user-attachments/assets/28a9ce17-9ca6-4a35-aef0-5da72efc3943)|
> refactor(Proof add): Currency field: add basic help icon + tooltip

- src/views/PriceValidationAssistant.vue
In the Price Validation Assistant, thanks to changes in the backend - see https://github.com/openfoodfacts/open-prices/pull/695 - we can now filter on the new `prediction_count` field, and return only Price tags with at least 1 prediction.
This will solve some (border case) issues, when the backend is processing new proof/price tags, and the price tags returned do not have any predictions (yet).
> refactor(Price validation): only show Price tags with a prediction

- src/components/ProductBarcodeTooLongChip.vue
- src/components/ProductCard.vue
- src/i18n/locales/en.json
- src/utils.js
Similar to the "invalid barcode" warning introduced in #622.
We add a new warning for barcodes that a length longer than the usual EAN13 (or EAN8).
(only a warning, doesn't prevent product/price creation, but will help users be more cautious of typos, especially in the Price Validation Assistant)
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/13a1babe-7855-48b4-9f9d-3d94c7ad9a1a)|![image](https://github.com/user-attachments/assets/18bdb5d6-e799-43c7-bc9e-c7166cfd1298)|
> refactor(Product): new warning if the barcode is too long (> 13 characters)

- src/components/ContributionAssistantPriceFormCard.vue
- src/i18n/locales/en.json
Following changes in the backend: https://github.com/openfoodfacts/open-prices/issues/702
- add a new "Not a price" error option
- move up the "Unreadable" option (used more often than "Truncated")
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/c912dacd-3cda-4e4d-bec3-c5a706b54af1)|![image](https://github.com/user-attachments/assets/4e538186-aa64-4e0e-9176-71f3460a9ed8)|
> refactor(Price tag): add a new error choice 'Not a price'

- src/components/LeafletMap.vue
- src/components/LocationSelectorDialog.vue
- src/i18n/locales/en.json
- Prettier tooltips as cards, with theme support
- Added an optional (hidden by default) select location button in tooltip, so users do not have to look in the list
| Before | After |
| ------- | ----- |
| ![Screenshot 2025-02-08 at 17-07-06 Open Prices](https://github.com/user-attachments/assets/2579b5aa-9e72-427b-b56d-9e646a60eeb5) | ![Screenshot 2025-02-08 at 16-59-19 Open Prices](https://github.com/user-attachments/assets/722f1c59-b13c-469c-9c34-d1d6683b877b) |
> feat(LocationMap): Display tooltips as cards and allow selection

- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
- src/services/api.js
Following changes in the backend - https://github.com/openfoodfacts/open-prices/pull/710 - we now give users the possibility to opt-out from price validation.
When uploading multiple proofs, users can uncheck the field, and their proof's price tags will not appear in the Price validation page.
|Before|After v1|After v2|
|-|-|-|
|![image](https://github.com/user-attachments/assets/2e33ac37-44a1-43b1-86f8-7459ecb647d2)|![Screenshot from 2025-02-12 20-11-43](https://github.com/user-attachments/assets/4b7a041c-7633-4c47-ab7a-80e22bd5bbb4)|![image](https://github.com/user-attachments/assets/647ff5ec-4394-44dd-ac85-f316c01a002b)|
> feat(Proof upload): allow to opt-out from price tag validation

- src/views/ContributionAssistant.vue
- src/views/PriceAddMultiple.vue
- In the 3rd step of the assistant, we display price tags with prices already added in a greyed-out way (disabled)
- While not being editable, these cards kept the same behavior as the other ones, meaning they also displayed the predicted content, instead of the actual added price
- This PR shows the actual added prices instead
> refactor(ContributionAssistant): display correct values for existing prices

- src/components/BarcodeScannerDialog.vue
- src/constants.js
- src/services/api.js
Allow users to search for barcodes with wildcard.
"Hidden" feature, not advertised.
The product data format is slightly different, did some super quick hacks in the meantime.
|Regular search|With wildcard|With 2 wildcards|
|-|-|-|
|![image](https://github.com/user-attachments/assets/2d15156b-9a47-48e2-8676-82f3ce4e87a4)|![image](https://github.com/user-attachments/assets/abf02ff0-3ebc-4288-825a-0ae72a76f3a4)|![image](https://github.com/user-attachments/assets/d455923f-2246-400a-9cec-f875ed1e4bd1)|
> feat(Barcode search): allow wildcard search thanks to search-a-licious

- src/components/ChallengeTimeline.vue
- After mid-day, challenge timeline shows that the challenge ended, when there's still a day left.
- It was only a visual bug, with no effects on stats, as far as I can tell.
- This fixes it
> fix(Challenge): Timeline: fix off-by-one end date error

- src/components/StatCard.vue
- src/views/Stats.vue
Following new stats in the backend: https://github.com/openfoodfacts/open-prices/pull/708
Changes in the stats page:
- add detailed stats per flavor
||Image|
|-|-|
|Before|![image](https://github.com/user-attachments/assets/017cd768-c7a0-4b15-aa55-7126d70d2527)|
|After|![image](https://github.com/user-attachments/assets/3ce0e4de-0af8-408f-a72f-5e61556bec08)|
> feat(Stats): display price count per product source (OxF flavors)

- src/components/HistoryCard.vue
Following a change in the backend, we now return the Price/Proof/Location source field: https://github.com/openfoodfacts/open-prices/pull/719
We can display this info in the `HistoryCard` in the `PriceDetail` & `ProofDetail` pages
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/2809fe7c-658d-492a-ba9b-b296c018cf84)|![image](https://github.com/user-attachments/assets/d4790838-a620-4438-bdce-3894336d8ca3)|
> refactor(History): show the price & proof source info

- src/i18n/locales/en.json
- src/views/Stats.vue
Following changes in the backend: https://github.com/openfoodfacts/open-prices/pull/728
Display 2 new global stats:
- price community count
- price consumption count
> refactor(Stats): new community & consumption price counts

- src/i18n/locales/en.json
- src/views/Stats.vue
2 changes in the stats page:
- new Miscellaneous section at the bottom
- show prices & proofs count per source - thanks to https://github.com/openfoodfacts/open-prices/pull/736
> refactor(Stats): new Misc section. Show prices & proofs count per source

- .github/workflows/deploy.yml
- .github/workflows/release-please.yml
- README.md
Renamed the main branch's name from `master` to `main`
- to match with the backend repo: https://github.com/openfoodfacts/open-prices
- to match with most of OFF's repos
https://github.com/github/renaming#renaming-existing-branches
Additional changes to reflect this renaming.
> build: rename main branch from 'master' to 'main'

- src/views/Stats.vue
Following changes in the backend: https://github.com/openfoodfacts/open-prices/issues/740
Display the new `price_location_country_count` stat
> refactor(Stats): new unique country stats (in Misc)

- src/i18n/locales/en.json
- src/views/Stats.vue
Following changes in the backend: https://github.com/openfoodfacts/open-prices/issues/738
Display the new `price_year_count` stat
> refactor(Stats): new unique year count stat (in Misc)

- src/components/ProofEditDialog.vue
- src/components/ProofFooterRow.vue
- src/components/ProofMetadataInputRow.vue
- src/components/ProofReceiptOnlineDeliveryCostsChip.vue
- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
- src/services/api.js
- src/views/PriceAddMultiple.vue
Following recent changes in the backend: https://github.com/openfoodfacts/open-prices/pull/724
- Display the new `Proof.receipt_online_delivery_costs` field in the proof form. Create & Edit; Only for receipts.
- New `ProofReceiptOnlineDeliveryCostsChip` component to display the delivery costs in the proof footer
|-|-|-|
|Proof form|![image](https://github.com/user-attachments/assets/b088c880-f2a2-4290-b1f7-547e5ccfc242)|![image](https://github.com/user-attachments/assets/1349ca02-ce51-4b05-a485-97a22b1ffa42)|
|Proof card|![image](https://github.com/user-attachments/assets/63a59089-444a-4413-9e45-96885b2b0a40)|![image](https://github.com/user-attachments/assets/fcbd485b-f07c-45a2-ad61-87da53347766)|
> feat(Proofs): Display the new receipt_online_delivery_costs field in the form

- src/utils.js
- src/views/Home.vue
Now that the first challenge is over, hide it from the Home page.
The banner will only be displayed if there is an ongoing challenge.
Note: we could think of more complex rules, for instance display the banner a few days before & after the challenge :bulb:
> refactor(Challenge): display Home banner only if ongoing challenge

- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/components/ProofMetadataInputRow.vue
- src/components/ProofUploadCard.vue
In the Proof & Price forms, we had 4 checkbox. Replacing them with switches.
- Proof: ready_for_price_tag_validation, owner_consumption
- Price: labels_tags, price_is_discounted
|-|-|-|
|Price form|![image](https://github.com/user-attachments/assets/f5f6caea-9f89-4b31-8d73-47ccaeb5ac68)|![image](https://github.com/user-attachments/assets/819dd518-f2f0-4b06-814f-0678a3ce4df3)|
> refactor(Forms): replace v-checkbox with v-switch (Proof & Price)

- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/components/ProofMetadataInputRow.vue
- src/components/ProofUploadCard.vue
- src/views/Settings.vue
Following #1437
Add some color to all the v-switch in the app
|-|-|-|
|Price form|![image](https://github.com/user-attachments/assets/64c3c94f-db76-4483-ab8f-a567bcaf161d)|![image](https://github.com/user-attachments/assets/8e38e7ab-72fa-45bb-a4ec-f431abced9b2)|
|Settings|![image](https://github.com/user-attachments/assets/ddd4578e-5724-467b-a6fa-782f695b614b)|![image](https://github.com/user-attachments/assets/cc819142-361a-4fe6-b655-076bd5cf1ea4)|
> refactor(Forms): add green color to v-switch (Proof, Price & Settings)

- src/components/PriceInputRow.vue
Similar to #1329.
Start adapting the Price form as well. Only change the text fields for now.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/5b15468b-0b77-476f-a87c-d62bef5afe08)|![image](https://github.com/user-attachments/assets/87aa384d-1ae2-4aab-b107-024fbf0bd8ed)|
> refactor(Price add): change look & feel of input text fields

- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
Following #1329 & #1441.
Replace the Price form select fields with their new look & feel (compact + outlined + label on top).
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/83c2e0bd-584c-4e7a-8716-cae78e23dd71)|![image](https://github.com/user-attachments/assets/9c5590d5-0f15-488a-a765-bb53f3f5dcbb)|
> refactor(Price add): change look & feel of input select fields

- src/components/PriceInputRow.vue
- src/components/ProductInputRow.vue
- src/components/ProofMetadataInputRow.vue
Add "required" asterisk next Proof/Price input label fields that are indeed required
- Proof date & currency
- Price price & category_tag
|Proof add|Price add|
|-|-|
|![image](https://github.com/user-attachments/assets/eee9e158-f68f-4d00-9665-bb7b73cafab0)|![image](https://github.com/user-attachments/assets/1cc76edf-ef65-4936-bf0a-0fd0e2cc0ccc)|
> refactor(Forms): add a red asterisk next to the required field labels

- src/assets/main.css
- src/components/HistoryCard.vue
- src/components/ProofEditDialog.vue
- src/components/ProofFooterRow.vue
- src/components/ProofMetadataInputRow.vue
- src/components/ProofUploadCard.vue
- src/components/ProofUserCommentChip.vue
- src/constants.js
- src/i18n/locales/en.json
- src/services/api.js
- src/views/PriceAddMultiple.vue
Thanks to the addition of the `Proof.owner_comment` field in the backend - https://github.com/openfoodfacts/open-prices/pull/748 - we display it in the frontend
- Proof upload form (link + toggle)
- Proof footer chip (simple chip, similar to #1435)
- Proof history card
|Page|Image|
|-|-|
|Proof form (create)|![image](https://github.com/user-attachments/assets/d67b2caf-cb80-4756-a071-3ff3fe25f8ce)|
|Proof form (after toggle)|![image](https://github.com/user-attachments/assets/ca39edd2-23bd-4721-8c37-91702cec0fb7)|
|Proof footer|![image](https://github.com/user-attachments/assets/38de4976-e082-4e68-8510-dd0e0d122542)|
|Proof history|![image](https://github.com/user-attachments/assets/0d3eac4a-82c5-4851-8875-9fee358c1588)|
> feat(Proofs): display the new owner_comment field (form, chip, history)

- src/views/UserDashboard.vue
Following the consumption/community split in the user dashboard (#1402), and changes in the backend (https://github.com/openfoodfacts/open-prices/issues/776 & https://github.com/openfoodfacts/open-prices/issues/777)
- replace the `Proof.type`  filter by `Proof.kind`
- replace the `Price.proof__type` filter by `Price.kind`
> refactor(User Dashboard): fetch price & proof data using the new `kind` filter

- src/constants.js
- src/views/PriceAddMultiple.vue
- src/views/ProofAddMultiple.vue
- src/views/ReceiptAssistant.vue
Following #1402 (2 tabs consumption & community)
- we change the URL of some of the CTAs that point to the dashboard, to pass the correct `tab` parameter
- we also adapt these buttons to have the URL display (thanks to the `:to`, instead of a `@click`)
> refactor(User Dashboard): point some CTAs directly to the correct tab. Use 'to' instead of 'click'

- src/components/ContributionAssistantPriceFormCard.vue
- src/components/ProofImageCropped.vue
- Did a deep dive on the price validation performances
- Profiling tools indicate that most of the time is spent on computing `HTMLCanvasElement.toDataURL` and `CanvasRenderingContext2D.drawImage`
--
- This PR replaces `toDataURL` with `toBlob`, which has way better performances
- `toBlob` requires the use of `URL.createObjectURL(blob)` to get a usable image, but that still seems to perform better, and it allows more control on cleanup with `URL.revokeObjectURL` (called when the price form card is unmounted)
--
- This PR also rounds numbers for `drawImage` performances, to avoid antialiasing computations
- However, most time spent is related to rendering the proof images in the canvas, which isn't very efficient if the user device doesn't include a GPU...
* The real solution probably …
> refactor(Crops): improve perfomances

- src/components/PriceInputRow.vue
- src/i18n/locales/en.json
Following #1128 (field added) & #1276 (allow 2 decimals)
And support in the backend with https://github.com/openfoodfacts/open-prices/issues/795 (allow 3 decimals)
> fix(Price add): Allow 'quantity bought' field to have 3 decimals

- src/components/ProofMetadataInputRow.vue
- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
- src/views/ProofAddMultiple.vue
- src/views/ReceiptAssistant.vue
Following #1394, we want to be more explicit to users about the use of AI.
We'll need to manage this in the backend.
For now we just show a readonly message.
> refactor(Receipt Assistant): show a readonly toggle indicating that AI will run on the image

- src/components/LocationInputRow.vue
- src/components/ProofMetadataInputRow.vue
- src/components/ProofUploadCard.vue
Following the addition of the 'Delivery costs' input field in the proof upload card - https://github.com/openfoodfacts/open-prices-frontend/pull/1427
We now only display it if the selected location is ONLINE.
> fix(Proof Upload): only show 'Delivery costs' field if an online location is selected

- src/i18n/locales/en.json
- src/store.js
- src/views/ProductDetail.vue
- src/views/Settings.vue
Following #1522
New settings to allow users to choose between the 4 price displays: list, table, map, chart.
> feat(Settings): allow users to set a default price list display

- src/views/ChallengeDetail.vue
- Using https://github.com/openfoodfacts/open-prices/pull/821 and https://github.com/openfoodfacts/open-prices/pull/813
- We can now simplify API calls to fetch Proofs and Prices matching a challenge
- This also fixes the issue of the proof count tallying every proof, instead of ones matching the challenge
> refactor(Challenge): use new tags api param

- src/components/ChallengeTakePicturesCard.vue
- src/components/ChallengeValidateCard.vue
Following #1537 & #1538
Make the new "challenge proof list" & "challenge price list" accessible via the stats cards
||Image|
|-|-|
|Before|![image](https://github.com/user-attachments/assets/877f78c8-b00e-4669-9b10-ce5f263cf2ac)|
|After|![image](https://github.com/user-attachments/assets/61a42d64-f549-4dac-83e7-4ddb4432e597)|
> refactor(Challenges): make total proof & price stat counts clickable

- src/components/ReceiptTableCard.vue
In the new Receipt Assistant (following #1501), we add the `ProofReceiptPriceCountChip` & `ProofReceiptPriceTotalChip` components at the footer of the price table.
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/319da660-28f1-42df-87fb-049a6a31e4b4)|![image](https://github.com/user-attachments/assets/4fba881b-fa92-42a0-9904-11170e480e12)|
> refactor(Receipt Assistant): show price count & price total below table

- package.json
- src/components/BarcodeScannerDialog.vue
- src/constants.js
- src/store.js
- src/views/Settings.vue
- vite.config.js
- Makes use of the barcode-scanner from https://github.com/openfoodfacts/openfoodfacts-webcomponents
- BarcodeScannerDialog uses the webcomponent by default, if the browser supports it, with a fallback on the previous scanner
- The settings page includes a new parameter to allow users to swap between libraries
- New scanner seems to be performing better on supported formats (ean-8 & ean-13), tests were made on Android Chrome
| Before | After |
| ---- | ---- |
| ![Screenshot_20250504-180858_Chrome](https://github.com/user-attachments/assets/81ee16b1-d9d5-4700-a18f-38edf874897e) | ![Screenshot_20250504-180817_Chrome](https://github.com/user-attachments/assets/2fa901dc-9b60-4f7e-a120-3f0a6eef818b) |
New settings parameter
- Fixes #1512
> feat(Barcode Scanner): use openfoodfacts-webcomponents (and allow user to switch back to html5-qrcode)

- src/components/ProductInputRow.vue
- src/views/ProductDetail.vue
Fixes #1544 (allowing to display non-en category tags, such as https://prices.openfoodfacts.org/products/fr:batavia)
> fix(Products): better manage non-en category tags

- src/assets/main.css
- src/components/ProofUploadCard.vue
- src/i18n/locales/en.json
The recently-added Receipt Assistant is hidden.
Here we show a nudge to users selecting the "receipt" proof type
> feat(Receipt Assistant): Add a callout-promo in the ProofUploadCard

- src/components/ProofUploadCard.vue
Following #1563
- Sometimes the proof_type param wasn't considered, and the proof type choice wasn't selected
> fix(PriceAddMultiple): always consider proof_type in Proof upload card

- src/views/ReceiptAssistant.vue
Same as the Contribution Assistant, allow loading the Receipt Assistant page with a `?proof_ids=` param
> fix(Receipt Assistant): fix init the assistant with a proof_id

- src/components/PriceAddLink.vue
- src/components/ProofActionMenuButton.vue
When owner of a receipt proof, there was an option to open it with the assistant.
But it was pointing to the Contribution Assistant. Not the Receipt Assistant.
> refactor(Receipt Assistant): in the proof action menu, change the link to point to the right assistant

- src/components/CategoryCard.vue
- src/components/PriceAlreadyUploadedListCard.vue
- src/components/PriceInputRow.vue
- src/components/PriceTable.vue
- src/components/ProofActionMenuButton.vue
- src/components/ProofFooterRow.vue
- src/components/ProofUploadCard.vue
- src/views/ProofDetail.vue
Following #1522 (new proof detail table view).
For receipts, display the quantity column (but only if the user is the proof owner)
||Image|
|-|-|
|Before|![image](https://github.com/user-attachments/assets/2b28b8bb-cb0f-4140-8e9f-22c66f786ccf)|
|After|![image](https://github.com/user-attachments/assets/6fd1a119-18be-4b7e-b375-6b1ce884aa42)|
> refactor(Proof detail): if the user is the receipt owner, display the quantity column

- src/components/ReceiptTableCard.vue
In the Receipt Assistant, add the Quantity column between the Price & Actions columns
> refactor(Receipt Assistant): display the quantity column

- src/components/ProofUploadCard.vue
- src/views/ContributionAssistant.vue
- src/views/PriceAddMultiple.vue
- src/views/ProofAddMultiple.vue
- src/views/ProofAddSingle.vue
- src/views/ReceiptAssistant.vue
v2 of #1568
Done in every page with steppers
- Proof upload card
- Proof add single & Proof add multiple
- Price add multiple
- Receipt Assistant
- Contribution Assistant
Pave the way for more text/description for each action (card = can add image, description...)
|-|-|-|
|Receipt Assistant|<img width="900" height="457" alt="image" src="https://github.com/user-attachments/assets/dc54f835-64aa-4c54-a16d-6a120d97ea23" />|<img width="900" height="353" alt="image" src="https://github.com/user-attachments/assets/d5a155bd-41aa-43f0-ae83-e3db412ab5e1" />|
> refactor(Steppers): last step (Actions): show actions as cards instead of buttons

- src/components/ProofTypeChip.vue
- src/utils.js
- src/utils/proof.js
Continue splitting the `utils.js` file
> refactor(Utils): move proof stuff to a dedicated file

- src/utils/proof.js
- src/views/PriceValidationAssistant.vue
- src/views/ProofPriceTagAssistant.vue
Following the refactoring in #1616 and the new `utils/proof.js` file.
And following the added complexity in #1606.
We move the identical code in both `ProofPriceTagAssistant` & `PriceValidationAssistant` in the utils file
> refactor(Utils): move price tag handling in the proof utils

- src/components/ReceiptTableCard.vue
- src/views/ReceiptAssistant.vue
- Newly created ReceiptItems were ignored because they weren't considered as valid items
- Also fixes linked issue: _"Justin told me recently that prices without a product name are not uploaded"_
- Edit button wasn't working on newly created ReceiptItems 
- Rollback two-way binding (see #1639) that was forcing users to open the edit menu, instead of making edits directly on the table (price and product were ignored)
- See videos in linked issue
- Fixes #1639
> fix(ReceiptAssistant): fix editing price and product in place & new item addition

- src/components/ChallengeCard.vue
Following a change in the backend - https://github.com/openfoodfacts/open-prices/pull/995 - we can now have challenges covering a specific list of locations
> refactor(Challenges): ChallengeCard: display the number of locations if used as a filter

- src/components/UserCard.vue
User card
- rename price_currency_count to currency_count (following https://github.com/openfoodfacts/open-prices/pull/1006)
- always show currency_count, location_type_osm_country_count, product_count & price_count (even if = 0)
|Before|After|
|-|-|
|<img width="447" height="132" alt="image" src="https://github.com/user-attachments/assets/2f36bca7-59e9-4e85-9629-1f0d8e74a8c0" />|<img width="447" height="132" alt="image" src="https://github.com/user-attachments/assets/983f5549-d7fd-44c7-aca8-f6b7ba734aea" />|
> refactor(User card): show all stats (even if 0 or 1)

- src/components/RankingTableCard.vue
- src/i18n/locales/en.json
- src/views/ChallengeDetail.vue
Following #1674
- limit ranking to 3 and hide rank column
- display new location rankings - thanks to https://github.com/openfoodfacts/open-prices/issues/1001
- display new product ranking - thanks to https://github.com/openfoodfacts/open-prices/issues/1003
- display the top 10 after clicking on a button ?
> refactor(Challenges): improve display of ranking stats

- src/views/ProofPriceTagAssistant.vue
- src/views/ReceiptAssistant.vue
mimic the logic we have in the Proof Price Tag Assistant.
> refactor(Receipt Assistant): avoid calling the proof API twice

- src/views/ProofPriceTagAssistant.vue
In the first step, only allow uploading PRICE_TAG proofs
> fix(Proof Price Tag Assistant): restrict to PRICE_TAG proofs

- src/views/ProofPriceTagAssistant.vue
- src/views/ReceiptAssistant.vue
- ProofPriceTagAssistant has a feature skipping wait time when the proof is older than a day.
- This was introduced in PR https://github.com/openfoodfacts/open-prices-frontend/pull/1331 with the idea that it's pointless waiting for an AI process that probably failed
- However, this skip also happened when new boxes were drawn, leading to errors because the frontend did not wait long enough.
- This PR rectifies this, by only skipping the wait time when the proof is first loaded. And fully waiting when new boxes are drawn.
> fix(ProofPriceTagAssistant): Properly wait when new boxes are drawn on old proofs

- src/components/PriceTable.vue
- src/components/RankingTableCard.vue
- src/components/ReceiptTableCard.vue
We currently have 3 table components:
- Price list display mode: #1522
- Receipt assistant table: #1394
- Ranking table: #1674
Set the number of rows displayed as "infinity", to display all available items (no pagination, footer hidden)
Closes #1550
> fix(Tables): display all items available

- src/components/PriceTable.vue
Price list "table display" component : #1522
The location ordering was broken. Fix it by ordering by location_id.
A v2 would be ordering by name (but there's an issue if mixing with online locations that have a website_url instead).
> fix(Price table): fix location column sort (v1: by id)

- src/components/ContributionAssistantDrawCanvas.vue
- The release of the product addition experiment (#1685) broke the display of wider proofs in the Proof Price Tag Assistant
- This PR adds computations for an ideal width and height, no matter the aspect ratio of the proof
| Before | After |
| ------- | ----- |
| <img width="1903" height="911" alt="Screenshot 2025-10-07 at 21-18-38 Open Prices" src="https://github.com/user-attachments/assets/68acf22b-3b26-4a76-b29b-1e1c071995ae" /> | <img width="1903" height="911" alt="Screenshot 2025-10-07 at 21-18-49 Open Prices" src="https://github.com/user-attachments/assets/458b1172-069a-4568-8f22-79f507516835" /> |
> fix(ProofPriceTagAssistant): no longer truncate wide proofs in canvas
