README.md
index.html
src/App.vue
src/components/Header.vue
src/routes.js
src/views/AddPrice.vue
src/views/Home.vue

- replace "About" page with "Add a price"
- cleanup header
- cleanup README

feat: Cleanup template

---

package-lock.json
package.json
src/services/api.js
src/views/SignIn.vue
yarn.lock

Following #4 
- use [VueUse](https://vueuse.org) instead of [js-cookie](https://github.com/js-cookie/js-cookie)
- header is now reactive

feat: make cookies reactive

---

CONTRIBUTING.md
README.md

- improve `README.md`
- add `CONTRIBUTING.md`

fix: readme

---

src/routes.js
src/views/AddPrice.vue
src/views/AddPriceHome.vue
src/views/AddPriceSingle.vue
src/views/SignIn.vue

- New "price create" home page to choose between single mode & receipt mode
- Simple "price create form" for single mode (no pictures nor scanning nor location search yet)
|Location|Image|
|---|---|
|Price create home page|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/53e32593-3403-4b56-9b8a-418ace406538)|
|Price create single mode form|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f71e730d-39e1-4b3e-ae9e-5cd0be72c28b)|

feat: Basic prices create form

---

src/views/AddPriceSingle.vue

following #13
wording, icons, init date
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f71e730d-39e1-4b3e-ae9e-5cd0be72c28b)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/c875f572-c751-43c9-8be5-e3c32067e109)|

feat: small improvements on price create form

---

src/components/LocationSelector.vue
src/services/api.js
src/views/AddPriceSingle.vue

Get location results with OpenStreetMap Nominatim

feat: price create form: add location selector

---

package.json
src/components/BarcodeScanner.vue
src/components/LocationSelector.vue
src/views/AddPriceSingle.vue
yarn.lock

- add `html5-qrcode` library
- add a barcode scanner inside a dialog component
- useful link : https://github.com/mebjas/html5-qrcode/blob/master/examples/vuejs/README.md

feat: price create form: add barcode scanner

---

.env
.env.local
.env.preprod
.env.prod
package.json

- new command `yarn preview`
- `.env` config for preprod & prod

build: deployment configuration

---

src/App.vue
src/components/Footer.vue
src/views/Home.vue
src/views/NotFound.vue

Simple footer with About & Github link.
Also improved slightly the home page.

feat: add a footer

---

.github/workflows/deploy.yml

Add automatic deployment in staging when merging to master.

chore: add automatic deployment config

---

src/views/AddPriceHome.vue
src/views/AddPriceSingle.vue
src/views/SignIn.vue

Show "snackbars" on : 
- signin success
- price create (single) success

feat: show success messages

---

src/services/api.js
src/views/AddPriceHome.vue
src/views/AddPriceSingle.vue

Price create form
- Simple file uploader to send a proof
- get the id in return, and add it to the form data
- improve page and seperate in two steps

feat: price create form: add simple proof image uploader

---

src/components/PriceCard.vue

Use toLocaleString to display the price value with currency depending on the price info & the user's locale.
Avoid hardcoded info.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

feat(price list): better display price with currency

---

src/services/api.js
src/views/AddPriceSingle.vue

When adding a price, store in the localStorage the currency.
So that we can pre-fill the currency during the next form add

feat(price create form): store last currency used in localstorage

---

src/services/api.js

- allow to unshift obj to localstorage item array
- allow to set a limit to the number of returned recent locations
- cleanup

feat: improve localstorage interactions

---

src/components/LocationSelector.vue
src/services/api.js
src/views/AddPriceSingle.vue

Changes to simplify the location selector : 
- hide the osm id & type fields
- avoid having to always click on "Find location" to select a location
- display recent locations as chips
- select a recent location by clicking on it
- improve location search text field + button
|Before|After|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f4ebf35b-2df5-4a78-a728-758ac6da87bb)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/23e41899-0423-4b21-951e-e4d0d98df451)|

feat(price create form): simplify location selector

---

src/components/Footer.vue
src/routes.js
src/views/Stats.vue

New stats page with 1 stat: "price count"
Available via a button in the footer

feat(stats): super basic stats page

---

src/components/PriceCard.vue
src/routes.js
src/services/api.js
src/views/PriceList.vue
src/views/ProductDetail.vue

When selecting a product from a PriceCard, we are now presented with a Product page:
- basic info
- last prices
API call made available thanks to this PR : https://github.com/openfoodfacts/open-prices/pull/100

feat(product detail): new basic Product detail page

---

src/services/api.js

Following #15
Small improvements on the location data fetched from Nominatim : 
- return more results (10 instead of 5)
- return address details
- filter out results that are not shops (list to be completed...)

feat: improve location data coming from Nominatim

---

package.json
src/components/LocationSelector.vue
yarn.lock

Location selector :
- add `leaflet` & `vue-leaflet` packages
- display a map with the search results to help the user visualize them

feat(price create form): add leaflet map to location selector

---

src/components/PriceCard.vue
src/routes.js
src/services/api.js
src/views/LocationDetail.vue
src/views/ProductDetail.vue

When selecting a location from a PriceCard, we are now presented with a Location page:
- basic info
- link to OpenStreetMap
- last prices
API call made available thanks to this PR : https://github.com/openfoodfacts/open-prices/pull/100

feat(location detail): new basic Location detail page

---

src/components/Header.vue
src/routes.js
src/views/UserDashboard.vue

When the user is logged in, new "Dashboard" page with : 
- his username
- his number of added prices
- his last added prices
|Header|Dashboard page|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/b33f4827-2065-4b04-8ded-b420c3655ac1)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/0e2c4085-065e-4e49-ab10-d87986e2010a)|

feat(user page): new basic Dashboard

---

package.json
src/main.js
src/store.js
yarn.lock

Thanks to [pinia-plugin-persistedstate](https://github.com/prazdevs/pinia-plugin-persistedstate) we can easily persist the new pinia store - #69 - to the user's localStorage

refactor: persist store to localstorage

---

src/components/PriceCard.vue
src/utils.js
src/views/LocationDetail.vue
src/views/ProductDetail.vue
src/views/UserDetail.vue

Price card v2 (v1 in #26)
Changes : 
- columns
- chips for basic info
- click on username to go to user page (thanks to #78 )

feat(price card): improve look & feel

---

src/data/labels-tags.json
src/views/AddPriceSingle.vue

Following #74 we also want to indicate if the raw product is organic or not.

feat(price create form): add label organic

---

src/data/origins-tags.json
src/views/AddPriceSingle.vue

Following #74, we want to indicate the origin of the raw product

feat(price create form): add origin field

---

src/data/category-tags.json

- add all potatoes
- don't include "fresh" versions of categories which are confusing
- remove some categories that don't make sense
Solves #87.

chore: update categories

---

.github/workflows/auto-assign-pr.yml
.github/workflows/semantic-pr.yml

- auto-assign PR
- check PR name

ci: add 2 PR github workflows

---

src/components/PriceCard.vue

|Before|After|
|---|---|
|![Screenshot from 2024-01-07 09-34-33](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/173c1fc3-e1ae-4850-90be-65b6efb86c7e)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/5c6e064f-cbd5-449f-9cde-db8030c90dbf)|

fix(price card): show location flag at the end

---

src/components/LocationSelector.vue
src/views/AddPriceSingle.vue

To accelerate price adding, we select by default the last selected location.
Removes 1 unnecessary click

feat(price create form): init location with last recent

---

src/services/api.js

Thanks to https://github.com/openfoodfacts/open-prices/pull/122 we can now fetch a list of products
This PR adds a `getProducts()` method

feat: new api to get the product list

---

src/components/LocationSelector.vue
src/store.js
src/utils.js
src/views/AddPriceSingle.vue
src/views/LocationDetail.vue

Various improvements on the location selector : 
- add a remove button per recent location (but seems to be only visible on large screens)
- clear button ui
- refactor the location name function
- reduce the size of the recent location name
- fix a bug when the same location was selected twice

feat(price create form): improve location selector (remove button, location name, fixes)

---

src/components/Header.vue
src/router.js
src/services/api.js
src/store.js
src/views/Home.vue
src/views/UserSettings.vue

Simple user settings page to manage default values and offload choices in the rest of the app.
For now the user can only change it's default currency.

feat(user settings): new user settings page

---

src/router.js
src/views/ProductList.vue

Following #114 
And thanks to https://github.com/openfoodfacts/open-prices/pull/119 we now have a new field `Product.unique_scans_n`
Creation of a new `/products` page ordered by most scanned
This page is accessible from the left drawer

feat(product list): new product list page ordered by popularity (unique_scans_n)

---

src/components/PriceCard.vue
src/components/ProductCard.vue
src/views/AddPriceSingle.vue
src/views/BrandDetail.vue
src/views/ProductDetail.vue
src/views/ProductList.vue

We were overusing the `PriceCard` in context where only the product info was displayed.
Better to create a seperate `ProductCard`, with the same logic.
TODO : continue refactoring and simplify both components

feat(product card): new ProductCard, seperate with PriceCard

---

src/services/api.js

Thanks to https://github.com/openfoodfacts/open-prices/pull/138 we can now fetch a list of locations
This PR adds a `getLocations()` method

feat: new api to get the location list

---

src/services/api.js

Thanks to https://github.com/openfoodfacts/open-prices/pull/147 we can now fetch a list of users
This PR adds a `getUsers()` method

feat: new api to get the user list

---

src/views/Stats.vue

Stats
- add user total
- add user with price total
- add location with price total (ref #140 - should be identical to location total)

feat(stats): new user total stats

---

crowdin.yml

feat(i18n): Crowdin config

---

src/constants.js
src/i18n/locales/de.json
src/i18n/locales/en.json
src/i18n/locales/es.json
src/i18n/locales/fr.json
src/i18n/locales/it.json
src/i18n/locales/nl.json
src/i18n/locales/pt.json

feat(i18n): add languages de nl it pt and update es fr

---

src/components/PriceCard.vue
src/i18n/locales/en.json
src/router.js
src/services/api.js
src/views/AddPriceHome.vue
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

New url `/add/multiple`
|Done|With new price form|
|---|---|
|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/9400f88a-878b-4daa-9238-c67be5e0aaf0)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/e5e4eb08-2c93-49c7-b415-5bad63e20d92)|

feat(batch create form): first simple batch mode to add multiple prices from a single proof

---

.env.local
.env.preprod
.env.prod
src/i18n/locales/en.json
src/views/ProductDetail.vue

Add a share button on the Product detail page

feat(share): simple share button on Product Detail

---

src/views/BrandDetail.vue
src/views/LocationDetail.vue
src/views/UserDetail.vue

Following #200
- add share button to `LocationDetail` & `BrandDetail` & `UserDetail`
- add OFF link in `UserDetail`

feat(share): add new button to other detail pages

---

.github/workflows/top-issues.yml

- ci: Automatically compute top issues

ci: Automatically compute top issues

---

.github/labeler.yml
.github/workflows/labeler.yml

ci: PR labeler

---

src/components/PriceFooter.vue
src/components/ProofCard.vue
src/components/RelativeDateTimeChip.vue
src/i18n/locales/en.json
src/router.js
src/views/UserDashboard.vue
src/views/UserDashboardProofList.vue

Following #244 
Allow logged in users to view their recently uploaded proofs

feat(dashboard): new page with user proofs

---

src/i18n/locales/en.json
src/views/BrandDetail.vue
src/views/LocationDetail.vue
src/views/LocationList.vue
src/views/Stats.vue
src/views/UserDashboardPriceList.vue
src/views/UserDashboardProofList.vue
src/views/UserDetail.vue
src/views/UserList.vue

- added a few translation keys

refactor(l10n): translation cleanup

---

src/constants.js

The location search sometimes returns places that are not shops...

fix(location selector): filter out additional place types

---

src/utils.js
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

Thanks to #273 we now have translated categories.
We can display the corresponding category list depending on the user locale

feat(l10n): translate category list in price add form depending on user locale

---

src/components/PriceCard.vue
src/utils.js
src/views/ProductDetail.vue

Following #273 we now have translated categories.
Bug when fetching correct product category

fix: fix get category name

---

src/components/PriceCard.vue
src/components/PriceCountChip.vue
src/components/ProductCard.vue
src/components/ProofCard.vue
src/i18n/locales/en.json
src/views/LocationDetail.vue
src/views/LocationList.vue
src/views/UserDetail.vue
src/views/UserList.vue

Refactor code and create a new `PriceCountChip` component
Add this component to the `ProofCard` - thanks to https://github.com/openfoodfacts/open-prices/pull/185

feat: add price_count to ProofCard (create new PriceCountChip component)

---

src/components/PriceProof.vue
src/components/ProofCard.vue
src/components/ProofFooter.vue
src/i18n/locales/en.json
src/views/UserDashboardProofList.vue

Improvements on proof display : 
- new `ProofFooter` component
- show footer in price proof dialog
- make dialog image scroll (instead of the full card)
- better display the proof type

feat(proof card): better display proofs

---

src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

Price value input : set the minimum value to 0

fix: price value must be positive

---

package.json
src/i18n/locales/en.json
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue
yarn.lock

- new JS library [ExifReader](https://github.com/mattiasw/ExifReader) to get the gallery image's `DateTimeOriginal`
- parse the date
- if different from today, update the price create form date (single & multiple mode)

feat: read gallery image exif date (and update if not today)

---

src/i18n/locales/en.json

- fix: Clarify that it wont open existing proofs

fix: clarify that gallery won't open existing proofs

---

data/languages/generate_languages.py
src/i18n/data/languages.json

Following #338 
- Added/corrected some language data
- Better visual file output

fix(l10n): improve language script

---

package.json
yarn.lock

Upgrade `vue` for dynamic import of components to work in #349 
v3.3.9 --> v3.4.19

build: upgrade Vue

---

src/views/BrandDetail.vue

- fix dynamic import for page brandDetail following PR #349

fix: typos in dynamic import (ref #349)

---

src/services/api.js

Thanks to https://github.com/openfoodfacts/open-prices/pull/228

feat(api): new getProofById

---

src/services/api.js

Thanks to https://github.com/openfoodfacts/open-prices/issues/181 there is now a backend endpoint to update (PATCH) a price.
Add a new `updatePrice()` method in the frontend api
Part of #402

feat(api): new updatePrice method

---

src/constants.js
src/i18n/locales/en.json
src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/ProductList.vue

Similar to #409, but for product ordering options

refactor(l10n): allow translation of product ordering options

---

src/constants.js
src/i18n/locales/en.json
src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/LocationDetail.vue
src/views/ProductDetail.vue
src/views/ProductList.vue
src/views/UserDetail.vue

Similar to #410 & #409 but for the filter(s)

refactor(l10n): allow translation of filtering options

---

src/components/ProductCard.vue
src/components/ProductCategoriesChip.vue
src/components/ProductLabelsChip.vue

Following #367
Move the chips (and dialogs) to their own components

refactor(product): new ProductCategoriesChip & ProductLabelsChip

---

src/components/PriceCard.vue
src/components/ProductCard.vue

refactor(product): if product missing, hide categories & labels

---

src/components/PriceCard.vue
src/components/PriceOrigins.vue

refactor(prices): move origin to own chip

---

src/components/PriceCard.vue
src/components/PriceLabels.vue

refactor(prices): move label to own component

---

src/components/ProofCard.vue

- PR #404 did not set the edit button properly

fix: proof edit button sliding

---

src/components/PriceFooter.vue
src/components/PriceLocationChip.vue

Move the price location code to a dedicated `PriceLocationChip`
Cleanup the `PriceFooter`, to add in the near future the Edit capability

refactor(price): new PriceLocationChip component

---

src/components/PriceFooter.vue
src/components/PriceOwnerChip.vue

Move the price owner code to a dedicated `PriceOwnerChip`
Cleanup the `PriceFooter`, to add in the near future the Edit capability

refactor(price): new PriceOwnerChip component

---

src/components/PriceActionMenuButton.vue
src/components/PriceEditDialog.vue
src/components/ProofEditDialog.vue
src/i18n/locales/en.json
src/views/AddPriceSingle.vue

Following #442
First basic edit price form. Only price data for now.
Todo : update underlying price afterwards (futur PR)

feat(price): basic edit form if user is owner

---

src/components/ProofCard.vue
src/components/UserRecentProofsDialog.vue
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

Errors in the console regarding `ProofCard`
- fixed by adding the `emits` param to the component
- improved the wording

fix: remove errors on Proof card emits

---

src/components/ProofFooter.vue
src/components/ProofTypeChip.vue

Move the proof type code to a dedicated `ProofTypeChip` component
Simplify `ProofFooter`

refactor(proof): new ProofTypeChip component

---

src/views/LocationDetail.vue
src/views/ProductDetail.vue

Use `v-alert` for error messages
||before|after|
|---|---|---|
|ProductDetail|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/f55587ad-74c4-483d-9288-e982ef93891b)|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/9411cd92-851a-4850-9d34-66e99f748f2a)|
|LocationDetail|||

refactor: move missing error messages in alerts

---

src/components/OpenStreetMapLink.vue
src/constants.js
src/views/LocationDetail.vue

Similar to #435
New `OpenStreetMapLink` component

refactor: new OpenStreetMapLink component

---

src/components/ProductFilterMenu.vue
src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/ProductList.vue

- new `ProductFilterMenu` component
- use in `BrandDetail`, `CategoryDetail`, `ProductList`
- change button style (round)

refactor: new ProductFilterMenu component

---

src/components/UserCard.vue
src/views/UserDetail.vue
src/views/UserList.vue

- new `UserCard` component
- use in `UserList` & `UserDetail`

refactor: new UserCard component

---

src/components/LocationCard.vue
src/views/LocationDetail.vue
src/views/LocationList.vue

- new `LocationCard` component
- use in `LocationList` & `LocationDetail`

refactor: new LocationCard component

---

src/assets/main.css
src/components/LocationCard.vue
src/components/PriceCard.vue
src/components/PriceFooter.vue
src/views/LocationDetail.vue
src/views/SignIn.vue

When a user signed in with an uppercase, we still had issues for edit actions, as the typed in username was stored.
Other minor changes
- reduce the width of the sign in form on bigger screens
- bug fixes & cleanup

fix(Sign In): set username to lowercase

---

src/components/ChangeCurrencyDialog.vue
src/components/PriceEditDialog.vue
src/components/PriceInputRow.vue
src/i18n/locales/en.json
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

- New `PriceInputRow` component
- use in both single & multiple add price forms
- also use in price edit form
- allows the user to edit the currency

refactor: new PriceInputRow component

---

src/components/ProductQuantityChip.vue

Better display the "product quantity chip" if the product quantity is higher than 1000.

refactor(products): show kg/L if quantity > 1000

---

src/components/PriceCard.vue

Similar to #545, but this time in the `PriceCard`

fix(price): fix display and translation of price category name

---

src/components/LocationSelectorDialog.vue
src/constants.js
src/views/Search.vue
tests/e2e/spec.cy.js
tests/fixtures/products_3011360030498.json

Improvements on the search page: 
- hide keyboard on submit
- hide keyboard on barcode scanner
- update url on search (and allow searching directly with the url param)
- reduce a bit padding

refactor(Search page): Many small improvements on the search form

---

src/components/LocationCard.vue
src/components/LocationOSMIDChip.vue
src/components/LocationSelectorDialog.vue

refactor(location): new LocationOSMIDChip component

---

src/components/LocationCard.vue
src/components/LocationOSMIDChip.vue
src/components/LocationOSMTagChip.vue
src/components/LocationSelectorDialog.vue
src/utils.js
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

Following #600 & #601
New `LocationOSMTagChip` component

refactor(location): new LocationOSMTagChip component

---

package.json
src/components/UserRecentProofsDialog.vue
src/constants.js
src/services/api.js
tests/e2e/spec.cy.js

See https://github.com/openfoodfacts/open-prices/issues/302
Will be useful to differentiate the apps that interact with the API and create the prices (web app, mobile, third party, Postman, ...)

feat(API): send the app_name param in every API call

---

src/views/AddPriceMultiple.vue

Small improvements on the price add multiple form: 
- always show the card with created prices (even if there is no prices created yet ; to avoid avoid the add form change column)
- allow adding price by pressing enter

refactor(price add multiple): small improvements on the form

---

src/components/PriceInputRow.vue
src/components/ProductInputRow.vue
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

Following #85, make the `origin` field optional
Also refactored the form validation mecanisms
After #609 we're starting to have categories that do not have any origins (croissants, bread...)

refactor(price add): make product origin optional

---

src/components/LocationSelectorDialog.vue
src/constants.js
src/services/api.js
src/utils.js

Offer the possibility to search by node/way/relation ID

feat(location search): if the user searches by ID, then do a lookup with Nominatim

---

src/components/PricePriceRow.vue
src/utils.js

See title :)
||Image|
|---|---|
|Before|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/43d85d2f-3907-48a7-a11a-40e436375b73)|
|After|![image](https://github.com/openfoodfacts/open-prices-frontend/assets/7147385/4b19767f-d04e-4c26-8eb0-a82c9f35a613)|

refactor(price): always show prices with 2 decimals

---

src/services/api.js
src/views/AddPriceMultiple.vue

See https://github.com/openfoodfacts/open-prices/issues/322
We're going to have proof dates soon, if the info is available, then init the price form date with it.
Other cleanup

refactor(proof): On existing proof selected, init with proof date

---

src/components/ProofInputRow.vue
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

similar to #495 & #611
- new `ProofInputRow` component
- use in both single & multiple add price forms

refactor(price add): new ProofInputRow component

---

src/components/LocationInputRow.vue
src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue

similar to #495, #611 & #632
- new `LocationInputRow` component
- use in both single & multiple add price forms

refactor(price add): new LocationInputRow component

---

src/components/PriceEditDialog.vue

Following #645
Disallow the user to change an existing price date & currency (now that this data is linked to the proof)

refactor(price edit): hide/disable price date & currency changes

---

src/views/DateDetail.vue

Following the new Date detail page #675 
Add links to date year & date month

feat(Date detail): add chips to navigate to year & month

---

src/components/OpenFoodFactsLink.vue
src/components/UserActionMenuButton.vue
src/components/UserCard.vue
src/views/UserDetail.vue

In the User card (and User details), move the "Open Food Facts link" to a new `UserActionMenuButton`
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/65c58c98-fb45-4469-bcaa-66eaf166a240)|![image](https://github.com/user-attachments/assets/c4ae10b9-7074-4345-87d1-a2e840a858d7)|

refactor(User card): new action menu with OFF link

---

src/components/ProductActionMenuButton.vue
src/components/ProductCard.vue
src/views/ProductDetail.vue

similar to #696
In the Product card (and Product details), move the "Open Food Facts link" to a new `ProductActionMenuButton`

refactor(Product card): new action menu with OFF link

---

src/components/BrandCard.vue
src/views/BrandDetail.vue
tests/e2e/spec.cy.js

- new  `BrandCard` component
- add tests

refactor(Brand detail): new BrandCard component

---

src/components/BrandActionMenuButton.vue
src/components/BrandCard.vue
src/views/BrandDetail.vue

Following #712 
- new `BrandActionMenuButton` component
- use in `BrandDetail`

refactor(Brand Card): new action menu with OFF & Share links

---

src/components/DateCard.vue
src/components/PriceCountChip.vue
src/utils.js
src/views/DateDetail.vue
tests/e2e/spec.cy.js

- new  `DateCard` component
- add tests

refactor(Date detail): new DateCard component

---

src/components/DateActionMenuButton.vue
src/components/DateCard.vue
src/views/DateDetail.vue

Following #712
- new `DateActionMenuButton` component
- use in `DateDetail`

refactor(Date Card): new action menu with Share link

---

src/components/BrandCard.vue
src/components/CategoryCard.vue
src/components/ProductCountChip.vue

refactor: new ProductCountChip component

---

src/views/AddPriceMultiple.vue

feat(Price add): When selecting an existing proof, fetch its existing prices

---

src/components/PriceActionMenuButton.vue
src/components/PriceCard.vue
src/components/PriceFooterRow.vue
src/i18n/locales/en.json

Now always show the PriceCard action menu, and display a link to the product's OFF page

feat(Price card): new action to view product OFF page

---

src/components/PriceInputRow.vue
src/components/PricePriceRow.vue
src/views/AddPriceMultiple.vue

When a user inputs a new price, display the price per unit below.

feat(Price add): display hint with price per unit

---

src/components/ProductInputRow.vue
src/i18n/locales/en.json
src/views/AddPriceMultiple.vue

Prevent (softly) users to add duplicate prices for the same proof

feat(Price add): if an existing product is found, show a warning

---

.github/workflows/labeler.yml

Reverts openfoodfacts/open-prices-frontend#735
Hard to understand the new format, lots of errors, see this thread for context : https://github.com/actions/labeler/issues/715

chore(deps): revert bump actions/labeler from 4 to 5

---

src/components/CountryCard.vue
src/components/LocationCountChip.vue
src/i18n/locales/en.json
src/router.js
src/views/CountryDetail.vue

- new `LocationCountChip` & `CountryCard` components
- new `CountryDetail` page with url `/countries/France`

feat(Country detail): new basic Country detail page

---

src/views/CountryDetail.vue

Following #766. Similar to #773

refactor(Country detail): add map display option

---

.github/workflows/release-please.yml

Reverts openfoodfacts/open-prices-frontend#736

chore(deps): revert bump GoogleCloudPlatform/release-please-action from 3.7.13 to 4.1.3

---

package.json
src/components/PriceInputRow.vue
src/components/ProofInputRow.vue
yarn.lock

2nd part of #779
This time with a upgrade of vuetify : from `3.4.6` to `3.7.0`
and devDependencies
Also solved a problem with `v-file-input`. see discussion here : https://github.com/vuetifyjs/vuetify/issues/17687

chore(deps): Update packages (vuetify v3.7.0)

---

src/components/PriceActionMenuButton.vue
src/i18n/locales/en.json
src/router.js
src/services/api.js
src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/LocationDetail.vue
src/views/PriceDetail.vue

New page to view a single price (by id)

feat(prices): new Price detail page

---

src/components/FilterMenu.vue
src/constants.js
src/i18n/locales/en.json
src/views/LocationList.vue

Similar to existing filter in the `ProductList` & elsewhere

feat(locations): add filter by price_count

---

src/components/FilterMenu.vue
src/constants.js
src/i18n/locales/en.json
src/views/LocationList.vue
src/views/UserList.vue

Similar to #814 but in the `UserList` page

feat(users): add filter by price_count

---

src/views/LocationList.vue
src/views/PriceList.vue
src/views/ProductList.vue
src/views/UserList.vue

Following #832 
Add infinite scroll to ProductList, UserList & LocationList

feat(list pages): replace load more with infinite scroll

---

src/components/ProductLabelsDialog.vue
src/router.js
src/views/LabelDetail.vue

New `/labels/:labelId`page
When clicking on a product label, navigate to this new page

feat(label detail): new label detail page

---

src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/CountryCityDetail.vue
src/views/CountryDetail.vue
src/views/DateDetail.vue
src/views/LabelDetail.vue
src/views/LocationDetail.vue
src/views/LocationList.vue
src/views/PriceList.vue
src/views/ProductDetail.vue
src/views/ProductList.vue
src/views/ProofDetail.vue
src/views/UserDetail.vue
src/views/UserList.vue

Following #833 for "list pages", do the same for "detail pages"

feat(detail pages): replace load more with infinite scroll

---

src/views/CountryCityDetail.vue
src/views/Home.vue
src/views/LabelDetail.vue
src/views/LocationDetail.vue
src/views/LocationList.vue
src/views/ProductDetail.vue
src/views/ProductList.vue
src/views/UserDashboardPriceList.vue
src/views/UserDashboardProofList.vue

2 remaining pages : user price list & user proof list
Closes #529

feat(dashboard): replace load more with infinite scroll

---

src/views/BrandDetail.vue
src/views/CategoryDetail.vue
src/views/CountryCityDetail.vue
src/views/CountryDetail.vue
src/views/DateDetail.vue
src/views/LabelDetail.vue
src/views/LocationDetail.vue
src/views/LocationList.vue
src/views/ProductDetail.vue
src/views/ProductList.vue
src/views/ProofDetail.vue
src/views/UserDashboardPriceList.vue
src/views/UserDashboardProofList.vue
src/views/UserDetail.vue
src/views/UserList.vue

When reaching the end of the page (no more data to load), there was the loading component that was still showing

fix: fix infinite scroll when reaching the end

---

src/views/CategoryDetail.vue

Title.
This is a super simple PR just to get used to the codebase :)
fixes #841

fix(Category detail): properly refresh the list when choosing another category

---

src/views/BrandDetail.vue

Similar to #844, but when switching from 1 brand to another

fix(Brand detail): properly refresh the list when choosing another brand

---

src/components/Footer.vue
src/i18n/locales/en.json
src/router.js

- Drawer: add link to /stats
- Footer: add icons to buttons, put Stats before About

refactor(drawer): add link to stats page

---

src/components/StatCard.vue
src/i18n/locales/en.json
src/views/Home.vue
src/views/Stats.vue

New `StatCard` component
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/69de056e-1f01-4d9a-89ef-ac254eb09fdb)|![image](https://github.com/user-attachments/assets/492ab8ae-5afc-46a2-8d14-4fdd6563162a)|

refactor(Stats): new StatCard component. Use in stats page

---

.env.preprod
.env.prod
index.html
public/browserconfig.xml
public/manifest.preprod.json
public/manifest.prod.json

Additional fixes following #906
See #364

fix: kill the landing page (remove remaining /app)

---

src/views/Stats.vue

- remove Location total & Proof total
- rename Location, Proof & User "With a price" to "Total"
- rename Price count per type following https://github.com/openfoodfacts/open-prices/pull/496
- add Proof count per type

refactor(Stats): remove some totals, add new count per proof type

---

src/views/AddPriceMultiple.vue
src/views/AddPriceSingle.vue
src/views/PriceList.vue
src/views/UserDashboard.vue

On price create done, redirect to the user's dashboard

refactor(Price add): On price add done, redirect to User Dashboard

---

src/components/FilterMenu.vue
src/constants.js
src/views/UserDashboardProofList.vue

In Dashboard  > My Proofs, add an extra filter by proof type

refactor(User dashboard): My proofs: add filter by type

---

src/components/FilterMenu.vue
src/components/UserRecentProofsDialog.vue
src/constants.js
src/views/LocationList.vue
src/views/UserDashboardProofList.vue

Allow filtering locations by type : OSM or ONLINE

refactor(Location list): new filter by location type

---

src/components/LocationActionMenuButton.vue
src/components/LocationCard.vue
src/components/LocationChip.vue
src/constants.js
src/i18n/locales/en.json
src/views/LocationDetail.vue

Update LocationCard, LocationDetail & LocationChip
|Location detail|Location Card/Chip|
|---|---|
|![image](https://github.com/user-attachments/assets/43d8fd36-03a6-402c-b3d6-b648ce3e4fd4)|![image](https://github.com/user-attachments/assets/056b45f8-e6ef-4f65-bc16-2ed647d46c60)|

refactor(Location card): manage ONLINE locations (title, hide OSM metadata, actions)

---

src/components/ProofEditDialog.vue
src/components/ProofInputRow.vue
src/components/ProofMetadataInputRow.vue

Renaming to prepare for new proof fields :drum:

refactor(Proof add): rename ProofDateCurrencyInputRow to ProofMetadataInputRow

---

src/assets/main.css
src/components/LocationInputRow.vue
src/components/ProductInputRow.vue
src/components/ProofImageInputRow.vue
src/components/ProofMetadataInputRow.vue
src/components/ProofTypeInputRow.vue
src/views/AddPriceMultiple.vue

Price add form: 
- better indicate which fields are mandatory or optional
- add labels for Product & Price
|Proof form|Product & price form|
|---|---|
|![image](https://github.com/user-attachments/assets/f5fdd601-dc9c-435a-aa9d-fba7fa4079af)|![image](https://github.com/user-attachments/assets/53199372-518c-44e0-838b-e479a8ecf47d)|

refactor(Price add): show red asterisk next to required field labels

---

src/components/LocationInputRow.vue
src/components/LocationRecentChip.vue
src/components/LocationSelectorDialog.vue
src/components/ProofInputRow.vue
src/services/api.js

New `LocationRecentChip` component
And make most of the changes to allow displaying recent online locations + selecting one + creating a proof with a recent one

refactor(Location selector): new LocationRecentChip component

---

src/components/LocationInputRow.vue
src/components/LocationSelectorDialog.vue
src/constants.js
src/services/api.js

LocationSelector : new tab to add Online shops
Note : need to manage uniqueness conflicts (adding an existing online shop...)

feat(Location selector): allow adding new online locations

---

src/router.js
src/views/About.vue
src/views/AddPriceHome.vue
src/views/LocationList.vue
src/views/PriceList.vue
src/views/ProductList.vue
src/views/Search.vue
src/views/SignIn.vue
src/views/Stats.vue
src/views/UserList.vue
src/views/UserSettings.vue

Following #927 where we created the `Breadcrumbs` component.
Here we add them in all the remaining pages.

refactor: add breadcrumbs to all remaining pages

---

src/components/ProductInputRow.vue
src/views/AddPriceMultiple.vue

Try to gain some vertical px space :)
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/b3e89309-a9bb-4628-a70c-1dc7ab740260)|![image](https://github.com/user-attachments/assets/95ae4fe0-8bf4-4191-9d8d-91387d203550)|

refactor(UI): gain some vertical space above submit button

---

src/components/ProofFooterRow.vue
src/components/ProofReceiptPriceCountChip.vue
src/components/ProofReceiptPriceTotalChip.vue

Following #977
Move existing chips to new `ProofReceiptPriceCountChip` & `ProofReceiptPriceTotalChip` components

refactor(Proof card): new components for receipt price_count & price_total

---

eslint.config.js
package.json
src/components/BarcodeScannerDialog.vue
src/i18n/locales/en.json
src/views/LocationList.vue
src/views/ProductList.vue
src/views/UserDashboardPriceList.vue
src/views/UserDashboardProofList.vue
yarn.lock

Fix some translation pluralization.
Install https://eslint-plugin-vue-i18n.intlify.dev `intlify/eslint-plugin-vue-i18n`

refactor(l10n): add new pluralization translations. Start cleaning unused translations

---

src/views/SignIn.vue

Some small improvements on the Sign in page:
- columns on bigger screens
- use rows (adds spacing)
- move submit button to the right + make it green
- password visibility toggle

refactor(Sign in): improve UI (columns, spacing, password visibility toggle)

---

src/views/UserDashboardPriceList.vue

Similar to other "price lists", add a filter & order menu in the User price list page.
Default order to last created (to match the dashboard page)

feat(User Dashboard): My prices: add filter & order menus

---

src/views/ProofList.vue
src/views/UserDashboardPriceList.vue
src/views/UserDashboardProofList.vue

Following #1118
Add the same proof filter mechanism as the one on the User Proof list page.

refactor(Price list): add filter by type & price_count

---

src/views/PriceList.vue

Similar to #1139 & #1136, but for the `/prices` page

refactor(Price list): add filter by type & show_last_month

---

src/components/PriceTypeChip.vue
src/components/ProofFooterRow.vue
src/components/ProofTypeChip.vue
src/constants.js
src/utils.js

Similarly to the existing `ProofTypeChip`, create a new `PriceTypeChip`.
Not used yed ! But maybe at some point in specific pages ? :thinking:

refactor(Prices): new PriceTypeChip component. improve ProofTypeChip

---

src/views/PriceValidatorAssistant.vue

- Same as https://github.com/openfoodfacts/open-prices-frontend/pull/1155 for Price Validator Assitant

feat(Price Validator Assistant): add support for product name gemini detection

---

src/components/CurrencyChip.vue
src/components/ProofFooterRow.vue
src/router.js
src/views/CurrencyDetail.vue

New `/currencies/<currency>`page
- accessible from the CurrencyChip
- displays prices with the given currency

feat(Currency detail): New currency detail page

---

src/components/CurrencyActionMenuButton.vue
src/components/CurrencyCard.vue
src/views/CurrencyDetail.vue

refactor(Currency detail): new CurrencyCard with share link

---

src/components/PriceAddLink.vue
src/components/ProofActionMenuButton.vue
src/i18n/locales/en.json

Closes #1194
Went with the "Open with the assistant" wording.
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/d2dd51f3-b5d7-45bc-a6ed-d8c28845966b)|![image](https://github.com/user-attachments/assets/b46a20a0-458d-47f7-9010-c0ddae1a39d2)|

refactor(Proofs): add action menu to open with the contribution asssitant

---

src/components/PriceFooterRow.vue
src/components/ProofChip.vue
src/components/ProofDialog.vue

Split the `ProofChip` component into two, and extract the dialog in a new `ProofDialog` component.
For future reuse

refactor(Proofs): new ProofDialog component

---

src/components/BarcodeManualInputDialog.vue
src/components/BarcodeScannerDialog.vue
src/components/LocationSelectorDialog.vue
src/components/PriceDeleteConfirmationDialog.vue
src/components/PriceEditDialog.vue
src/components/ProductBrandsDialog.vue
src/components/ProductCategoriesDialog.vue
src/components/ProductLabelsDialog.vue
src/components/ProofDeleteConfirmationDialog.vue
src/components/ProofDialog.vue
src/components/ProofEditDialog.vue
src/components/UserRecentProofsDialog.vue

Similar to #1193
Make all the dialog headers the same height & setup
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/bd018efb-31e5-41a8-862d-2bcc154d7b8c)|![image](https://github.com/user-attachments/assets/df181020-0d7a-4c91-9ab5-93709dcc76ef)|

 refactor(Dialogs): homogenize the dialog title & close icon setup

---

src/components/PriceInputRow.vue
src/components/ProductInputRow.vue
src/components/ProofMetadataInputRow.vue

refactor(Price add): switch all proof & price fields to density comfortable (slightly smaller)

---

src/services/api.js
src/views/PriceAddMultiple.vue
src/views/PriceAddSingle.vue

cleanup/refactoring when preparing the price payload before calling the API (create, update)

refactor(Price add): better cleanup payload before calling the API

---

src/assets/main.css
src/views/ProofAddMultiple.vue
src/views/ProofAddSingle.vue

Use the [v-stepper](https://vuetifyjs.com/en/components/steppers) component to show steps at the top of the "Proof add single" & "Proof add multiple" pages.
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/59fc6cd9-f7cb-429c-a9d5-492075980526)|![image](https://github.com/user-attachments/assets/d4ba871b-bd70-4017-8cd3-6eee8fbc6729)|

feat(Proof upload): add a stepper at the top to guide users

---

src/components/ProofUploadCard.vue
src/i18n/locales/en.json
src/views/PriceAddMultiple.vue
src/views/ProofAddMultiple.vue
src/views/ProofAddSingle.vue

Following #1249, we now have a dedicated "Done" page where we have room to put some CTA buttons :)

feat(Proof add): add explicit CTAs at the end

---

src/components/ProofUploadCard.vue

Better indicate to users the proof upload progress (especially when there are many images to upload)
|Before|After|
|---|---|
|![Screenshot from 2025-01-12 17-27-32](https://github.com/user-attachments/assets/5f0c697f-d12e-4a49-abfe-aacb673dfdbd)|![Screenshot from 2025-01-12 17-19-36](https://github.com/user-attachments/assets/237025c0-7148-447f-a9f3-5a7728cba8cd)|

refactor(Proof upload): add progress bar after clicking on Upload

---

src/components/LocationInputRow.vue

Improve a bit how we display the selected location
- use a chip to homogenize with how we display location info elsewhere in the app
- add some padding between the form button and the selected location
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/fad2a85e-d6fd-4f6e-85e0-2313459abe66)|![image](https://github.com/user-attachments/assets/e2621a88-de7b-45c8-8649-e79a1460bcd4)|

refactor(Proof upload): better display selected location

---

src/components/ProductInputRow.vue

Similar to #1290
||mode "Edit"|mode "Display"|
|-|-|-|
|Barcode|![image](https://github.com/user-attachments/assets/1db387ff-8985-46d8-a153-a070e88e4654)|![image](https://github.com/user-attachments/assets/01be0203-c4df-40dc-a265-a985980d5941)|
|Category|![Screenshot from 2025-01-20 02-10-27](https://github.com/user-attachments/assets/d1812936-78ab-4ec6-ac41-f89dd594c19a)|![image](https://github.com/user-attachments/assets/6c73ea99-318a-470e-9e4d-e46d4ad4b008)|

refactor(Product input row): new 'mode' prop to display the data in readonly

---

src/components/ContributionAssistantPriceFormCard.vue
src/views/PriceValidationAssistant.vue

Give a feedback to the user
- the loader show the action pending
- the overlay avoid double clicks

refactor(Price tag): when creating or dismissing the price tag, show an overlay + loader

---

src/components/PriceCategoryChip.vue
src/services/api.js
src/views/ContributionAssistant.vue
src/views/PriceValidationAssistant.vue

The Price Validation didn't manage well price tags that had no info on them.
Fixes the `getPriceOriginTagName` & `getPriceCategoryTagName`  errors.

fix(Price validation): fix origin & category display for raw products

---

src/views/CurrentChallenge.vue

- Moved end date to 20th of February

refactor(CurrentChallenge): Update end date

---

src/views/CurrentChallenge.vue

Add the challenge's category(ies) as chips.
Upcoming PR : make it cliquable

refactor(CurrentChallenge): display category tag

---

src/views/ContributionAssistant.vue

- Do not try to fetch price tags on receipts
- Only try to fetch price tags once on proofs older than a day
- This avoids the unnecessary wait message on step 2 (see issue below for screenshot)
- Fixes #1206

refactor(ContributionAssistant): Avoid wait on auto detection for old proofs

---

src/components/ChallengeTakePicturesCard.vue
src/i18n/locales/en.json

- This was a suggested addition during the meeting on January, 22nd.

refactor(Challenge): Repeat proof upload warning on challenge page

---

src/i18n/locales/en.json
src/views/Stats.vue

feat(Stats): new Experiments section, with challenges & prices with price tag count

---

src/components/BarcodeScannerDialog.vue
src/components/BrandCard.vue
src/components/CategoryCard.vue
src/components/ContributionAssistantPriceFormCard.vue
src/components/CurrencyCard.vue
src/components/DateCard.vue
src/components/LabelCard.vue
src/components/LocationCard.vue
src/components/PriceCard.vue
src/components/PriceFooterRow.vue
src/components/ProductCard.vue
src/components/ProductInputRow.vue
src/components/ProofCard.vue
src/components/ProofDeleteConfirmationDialog.vue
src/components/ProofDialog.vue
src/components/ProofEditDialog.vue
src/components/ProofFooterRow.vue
src/components/ProofUploadCard.vue
src/components/UserCard.vue
src/components/UserRecentProofsDialog.vue
src/views/ContributionAssistant.vue
src/views/PriceAddMultiple.vue

Same changes to all the cards with bottom right action menu buttons:
- new prop `hideActionMenuButton` to show/hide the button
- adapt the row width depending if the button is hidden or not

refactor(Action menus): add a hideActionMenuButton prop in all the cards with actions

---

src/components/PriceEditDialog.vue
src/components/ProductInputRow.vue
src/services/api.js

Improve the price edit dialog:
- for raw products, allow editing the category, origin & label
- also change the price per (unit or kg)
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/e8f9e275-37d5-4a29-a22f-7ba4c8917c1e)|![image](https://github.com/user-attachments/assets/ea6f991d-6144-4189-9184-a08430170413)|

feat(Prices): allow editing raw product category, origin, label & price_per fields

---

src/components/ProductSourceChip.vue

New chip to display from which source the product comes from (OFF, OBF, OPF, OPFF).
Not displayed anywhere yet

feat(Products): new ProductSourceChip to display the product's source (OxF)

---

src/components/LocationCard.vue
src/components/ProofCountChip.vue
src/components/UserCard.vue

- new `ProofCountChip` component
- use in `LocationCard` & `UserCard` components

refactor(Proofs): new ProofCountChip component

---

src/i18n/locales/en.json
src/views/Stats.vue

Thanks to https://github.com/openfoodfacts/open-prices/pull/716

refactor(Stats): Add the new price with_discount count

---

src/components/ChallengeBanner.vue
src/data/challenges.json
src/utils.js
src/views/CurrentChallenge.vue
src/views/Home.vue

Similarly to Reuses, move the Challenges (only 1 for now) in a dedicated JSON file
- Home: banner: fetch the first challenge
- CurrentChallenge: fetch the first challenge
Note: we'll be move this to the backend sometime soon: https://github.com/openfoodfacts/open-prices/issues/691

refactor(Challenge): move the configuration to a dedicated JSON file

---

src/components/ProofUploadCard.vue

Proof upload card: move up the location selector
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/4ffd33ab-e36a-4ee5-a165-511bdd5a013b)|![image](https://github.com/user-attachments/assets/6082cc9d-00d4-471f-b85a-8e99faf42d0f)|

refactor(Proofs): move up the location field above the image(s)

---

src/components/PriceEditDialog.vue
src/views/PriceAddMultiple.vue

Following the addition of the `Price.receipt_quantity` field in #1128.
This PR allows the price owner to edit the value.

feat(Prices): allow editing receipt quantity field

---

src/components/ChallengeCard.vue
src/views/ChallengeList.vue

- Following suggestion in https://github.com/openfoodfacts/open-prices-frontend/pull/1459#discussion_r2008474981

refactor(Challenges): challenge card

---

src/components/FilterMenu.vue
src/constants.js
src/i18n/locales/en.json
src/views/ChallengeList.vue

- Following suggestion in https://github.com/openfoodfacts/open-prices-frontend/pull/1459#discussion_r2008479596
- Drop the unnecessary filter, we won't have many challenges after all, might as well display them all

refactor(Challenges): Remove status filter + cleanup

---

src/components/OpenFoodFactsLink.vue

fix(OFF Link): use the user country_code instead of language_code for the URL prefix

---

src/components/PriceCard.vue
src/components/ProductCard.vue
src/components/ProductDetails.vue

Move common Product code from `ProductCard` & `PriceCard` to a new `ProductDetails` component

refactor(Products): new ProductDetails component

---

src/components/PricePriceRow.vue
src/components/PriceQuantityPurchasedChip.vue

Move existing code to a new `PriceQuantityPurchasedChip`
for reuse

refactor(Receipt Quantity): new PriceQuantityPurchasedChip component

---

src/i18n/locales/en.json
src/views/ChallengeList.vue

Following #1459
|Before|After|
|-|-|
|![image](https://github.com/user-attachments/assets/442699a4-d188-41de-b7f2-6678c580fdab)|![image](https://github.com/user-attachments/assets/77224493-d8f9-492d-8250-34f124312c88)|

refactor(Challenges): new section to list upcoming challenges

---

src/components/ProductDetails.vue
src/utils.js
src/utils/barcode.js
src/views/PriceValidationAssistant.vue
src/views/ProofPriceTagAssistant.vue

Continue splitting the `utils.js` file into subfolder/files

refactor(Utils): move barcode stuff to a dedicated file

---

src/components/PriceAlreadyUploadedListCard.vue
src/components/PriceInputRow.vue
src/components/PricePriceRow.vue
src/components/PriceTypeChip.vue
src/components/ProofReceiptOnlineDeliveryCostsChip.vue
src/components/ProofReceiptPriceTotalChip.vue
src/components/ReceiptTableCard.vue
src/utils.js
src/utils/price.js

Continue splitting the `utils.js` file

refactor(Utils): move price stuff to a dedicated file

---

README.md

docs: README promo for design team and files

---

src/i18n/locales/en.json
src/views/Experiments.vue
src/views/PriceAddSingle.vue
src/views/ProofAddSingle.vue

Applies for `/prices/add/single` & `/proofs/add/single`.
These pages are decommissioned/deprecated/unmaintained

refactor(Experiments): remove single price & proof upload. add "not maintained anymore" banner.

---

src/views/ReceiptAssistant.vue

We have timeout issues for long receipts

refactor(Receipt Assistant): Increase the time to fetch predicted prices (from 15s to 50s)

---

src/components/ChallengeCard.vue

Display the challenge's price/proof/location/product count

refactor(Challenges): display count stats in the ChallengeCard

---

src/views/ChallengeDetail.vue
src/views/Community.vue
src/views/Contribute.vue
src/views/Stats.vue

minor changes in the HTML of some views

refactor: remove when possible <br> (move <h2> inside <v-col>)

---

src/components/ChallengeCountChip.vue
src/components/CountryCountChip.vue
src/components/CurrencyCountChip.vue
src/components/UserCard.vue

move some code to dedicated components

refactor(User card): new CurrencyCountChip, CountryCountChip & ChallengeCountChip components

---

src/components/BarcodeScannerDialog.vue

fix(Barcode scanner): remove whitespaces with trim()

---

README.md

- docs: Update README with Open Prices API details
- Added section for Open Prices API information and compliance requirements.

docs: Update README with Open Prices API details

---

src/constants.js

refactor(Price List): when ordering by -date, add an extra -created ordering to avoid reordering on refresh

---

src/utils/date.js
src/views/ChallengePriceList.vue
src/views/LocationDetail.vue
src/views/PriceList.vue
src/views/ProductDetail.vue
src/views/UserDashboardPriceList.vue
src/views/UserDetail.vue

Following the refactoring in #1613 (new utils/date.js file)
Move "oneMonthAgoDate" logic there as well (duplicated in 6 components)

refactor(Utils): new date.oneMonthAgoDate method

---

src/services/api.js

fix(Settings): call setLastCurrencyUsed when the user uploads a proof (instead of creates a price)

---

src/components/DisplayMenu.vue
src/constants.js
src/views/CountryCityDetail.vue
src/views/CountryDetail.vue
src/views/ProductDetail.vue
src/views/ProofDetail.vue

The component was introduced in #695
New `show` prop, to explicitly set the desired display options

refactor(Display Menu): new prop to explicitly set the display options

---

src/components/PriceTable.vue
src/views/LocationDetail.vue

refactor(Location detail): add price display toggle (list or table)

---

src/views/UserDetail.vue

Similar to https://github.com/openfoodfacts/open-prices-frontend/pull/1543 & https://github.com/openfoodfacts/open-prices-frontend/pull/1729 & https://github.com/openfoodfacts/open-prices-frontend/pull/1733 & #1734

refactor(User detail): add price display toggle (list or table)

---

src/components/LocationSelectorDialog.vue
src/i18n/locales/en.json

Linked to #212
In the location selector, users sometimes struggle to find the right shop in OpenStreetMap.
(I also simplified the "results" mgmt)

refactor(Location selector): Help message displayed when 0 results (OpenStreetMap)
